### ISSUE TITLE
Properly message improper package imports

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1000]
DartPad will soon support a whitelist of packages that users can reference in their code. We need to make sure the error messages coming out of DartPad (presumably passthroughs from dart-services) properly communicate this.

**Comment by domesticmouse** [comment]
Part of this issue is going to be dealt with inside of https://github.com/dart-lang/dart-pad/issues/901

The more interesting question is how to deal with packages that can't be compiled to the web, like `dart:io`. Do you want the backend to specifically error out on non web targetable packages during the analysis call?

**Comment by domesticmouse** [comment]
I believe @srawlins has tidied this up. 

@RedBrogdon is the current state good enough to call this issue fixed?

**Comment by RedBrogdon** [comment]
Yes. DartPad is handling the issue both for compilation and analysis.
