### ISSUE TITLE
output failure

### ISSUE THREAD

**Issue by joaohudson** [dart-lang/dart-pad#1080]
the dart pad does not display program output either on console or HTML output.

**Comment by domesticmouse** [comment]
Hi @joaohudson,

It'd be helpful to understand what code you are executing, and what the URL of the DartPad instance you are using is. We have multiple experiences, each with different capabilities.

Thanks!

**Comment by joaohudson** [comment]
Link: https://dartpad.dartlang.org/

code:

void main() {
  print('output not displayed when pressing run');
}

**Comment by domesticmouse** [comment]
Curiouser and curiouser. What browser are you using? 

It works fine for me in Chrome 75.0.3770.51 on macOS 10.14.5.

**Comment by joaohudson** [comment]
My version is Chrome 74.0.3729.169 on windows 8.1

**Comment by domesticmouse** [comment]
I've got it also working on 74.0.3729.169 on macOS 10.14.5.

We shouldn't be triggering any OS level differences, I'd be more intrigued to see what happens when you run your browser without extensions. See [this page](https://developer.chrome.com/devtools/docs/clean-testing-environment) for more information.

**Comment by RedBrogdon** [comment]
I'm going to go ahead and close this for now. Feel free to reopen with more info.
