### ISSUE TITLE
Flutter for web proof of concept needed

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1098]
Rather than adding to the existing, dart:html playground UI, we might want to rewrite it with Flutter for web. Someone needs to take a day or two and get a basic idea of how possible this is and what the scope of work would be.

**Comment by devoncarew** [comment]
@jwren did some brief investigation and did run into issues (I don't have the details).

cc @ferhatb @yjbanov

**Comment by jwren** [comment]
I'll follow up on email.

**Comment by RedBrogdon** [comment]
See also: https://github.com/flutter/flutter/issues/32326

Looks like this is blocked for the time being.

**Comment by iapicca** [comment]
as flutter web matured maybe now 
"dart-pad" in "flutter web" is doable

**Comment by mrmcq2u** [comment]
Seems embedding a webview in a flutter-web application is possible now, is exploring this still on the table. 

Are there other blockers which havent been listed, I have seen rich text editors implemented in flutter but no editors focussed on code, is there a limitation with libtext preventing this from being feesible? 

There doesn't seem to be text editors implemented in flutter right now. Would be useful fro

**Comment by leecommamichael** [comment]
I'm currently writing an interactive book to teach Dart as a first language. I have already embedded DartPad in a simple flutter-web project on the beta channel (1.24.0-10.2.pre). 

The biggest hurdle is font/theming consistency between DartPad and the rest of the page, but that's fine-- it's a branded product and I get that.

Another problem is one that's well documented, iframe embeds (how I'm doing it currently) aren't part of Flutter's gesture arena, so there are weird situations where I'll be tapping to dismiss a Drawer and DartPad will take cursor focus instead of dismissing the Drawer.

**Comment by domesticmouse** [comment]
@leecommamichael I feel like your issue should be filed as a seperate new issue, as it is different to the bug you are commenting on, which is asking for a completely new DartPad UI implemented in Flutter.

**Comment by leecommamichael** [comment]
> @leecommamichael I feel like your issue should be filed as a seperate new issue, as it is different to the bug you are commenting on, which is asking for a completely new DartPad UI implemented in Flutter.

Oh man, I didn’t read carefully enough. Thank you for your careful response.

**Comment by devoncarew** [comment]
We have a proof of concept for this now.
