### ISSUE TITLE
Should Run use the visible code or only the "Dart" tab's code?

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dart-pad#1172]
The **Run** button should either run the code that's currently visible (e.g. the code in the **Solution** tab) or somehow indicate (by switching tabs?) that it's running the user's code.

To reproduce:

1. Go to https://jt-ww-1.firebaseapp.com/codelabs/async-await#exercise-2
2. Click **Hint**.
3. Click **Show solution**.
4. Click **Run**. The tests fail. This is where I stopped, assuming there was a bug in the codelab. :)
5. Copy the solution code into the **Dart** tab and then click **Run**. The tests work.

/cc @legalcodes

**Comment by RedBrogdon** [comment]
Should be easy enough to implement, possibly at the same time as #1119.

**Comment by galeyang** [comment]
Thanks for filing this issue! It's on my todo list for a while.

Since this may affect analytics (test results), I can think of two ways:

**Option 1**: The Run button runs the code that's currently visible (e.g. the code in the Solution tab) 

In the analytics, we add an extra tag to track the which tab is running because the solution code (without edits) should always pass the test. We may filter out this test result.

**Option 2**: The Run button run the users's code 

This means we need to somehow indicate (by switching tabs?) that it's running the user's code
Also maybe add a button to allow users quickly replace their code with solution?
For analytics, we may want to know whether a solution (and hint) is presented while users run the code. 

@jayoung-lee Do you have any suggestion from the analytics perspective?

**Comment by jayoung-lee** [comment]
I'd vote for option 1, and yes I think separating hint-run and code-run is a good idea. 

Either way, Analytics should match whatever the user thinks he/she is doing :)

**Comment by parlough** [comment]
Since https://github.com/dart-lang/dart-pad/issues/2808 dropped support for multiple files, there is only a "Dart" tab now.
