### ISSUE TITLE
When the statement contains '??' why doesn't check type?

### ISSUE THREAD

**Issue by HannibalKcc** [dart-lang/dart-pad#1195]
```
void main() {
  String a = 123 ?? '123'; // error just in runtime
  String b = 123 ?? 557; // error
  
  print(a);
  print(b);
}
```

I wrote the same code on Android Studio(with plugin Dart 183.6270 Flutter 38.1.1)，and Dart Analysis will not check type with ` ?? ` too.

I want to know if this is intentional? why?

**Comment by domesticmouse** [comment]
Hey @munificent, where is the right place to raise this issue?

**Comment by eernstg** [comment]
First, the underlying issue will go away when we add non-nullable types to Dart (because it's part of that effort to eliminate implicit downcasts).

Next, in the example you have an upcast and then a downcast: In `123 ?? '123'` the operand types are `int` and `String`, and the type of the expression is the least upper bound of the two, here `Object`. So you provide an expression of type `Object` where a `String` is expected, which is allowed, with a dynamic check. So it's a worst-case clash of implicit up- and downcasts. But given that the downcast will have to be explicit when we get non-nullable types, the issue will go away.

Among other things, you can pass `--no-implicit-casts` to the analyzer to detect this kind of situation today.

For issues with the Dart language as such, the right place to raise them is the language repository: https://github.com/dart-lang/language/issues.
