### ISSUE TITLE
Investigate running dart-services on GCE

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1199]
Description TODO @domesticmouse.

Deliverables for this are a short design doc and a proof of concept implementation.

**Comment by domesticmouse** [comment]
Some investigation has been accomplished. The path forward is either gVisor atop [COS](https://cloud.google.com/container-optimized-os/docs/) (Container Optimised OS) or Drawfork Debian. I'd prefer COS, because it is a more secure OS.

I have yet to put together a proof of concept. I more have a bunch of proofs of failed concepts. Closing this out for now as higher priority tasks are going to soak back end engineering time for the short term.
