### ISSUE TITLE
Add an alternate, "just output" UI mode to the embed for displaying Flutter UI

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1234]
It would be nice to have a DartPad layout that first showed the running Flutter / Web output and had a "View Code" button at the bottom. This would be useful for embedding into documentation where showing the output is the main goal. 

example use-case: https://flutter-animations-cheat-sheet.codemagic.app/

**Comment by RedBrogdon** [comment]
+1.

I could have sworn we created an issue for something like this on the playground, but looking through the existing stack, I don't see anything.

I'm going to tweak the title of the issue to reflect that this is for the embedded UI, and create another for the playground.

**Comment by ferhatb** [comment]
+1 It would be nice to ship optimized dart2js output in these scenarious (~300K gzipped). Not only will they perform better, but faster load time.

**Comment by tc** [comment]
Can this be done by editing the embed-flutter.html file to hide the code part?

**Comment by RedBrogdon** [comment]
Yes. We'd want to create an additional HTML file (embed-showcase.html or something), but that would be the basic idea. It's possible that some of the code in `lib/embed.dart` might also need to be updated as a result, since it's a shared file for all the embedded HTML layouts.

@ferhatb's suggestion of using dart2js would be a more significant change, though definitely also valuable.
