### ISSUE TITLE
"show issues" overlay gets in the way with the Flutter app UI

### ISSUE THREAD

**Issue by clocksmith** [dart-lang/dart-pad#1235]
See how it interrupts with the FAB in the starter demo:

<img width="2260" alt="Screen Shot 2019-08-28 at 2 40 21 PM" src="https://user-images.githubusercontent.com/591699/63883371-0a86c480-c9a2-11e9-9416-3d45f85474e8.png">

**Comment by RedBrogdon** [comment]
Valid complaint. I don't think it's been a problem before simply because we haven't tested anything with a FAB or other widget in that corner. 

One solution would be to add a transition that makes "no issues" slide out of view or otherwise disappear after a few seconds.

**Comment by gspencergoog** [comment]
I've seen this come up with a bunch of the samples I've been converting.

Having it slide out the way would be fine.  Or, move it to the middle of the button the opens/closes the console.

**Comment by parlough** [comment]
The current DartPad frontend surfaces diagnostics in a much different fashion, so I'm going to close this as stale. But please file any UX issues in relation to the newest UI.

https://github.com/dart-lang/dart-pad/issues/2999 covers some issues with how the newest UI surfaces API docs and analyzer diagnostics, so that might be a good reference for current thoughts as well.

Thanks all!
