### ISSUE TITLE
Detect if localStorage is available and display dialog

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#1237]
See https://github.com/dart-lang/site-www/issues/1838 for more information

Related issues:

#1520
#1473

**Comment by kwalrath** [comment]
Could we make this higher than p3? When people run into this issue, it's a really bad experience.

**Comment by kwalrath** [comment]
I'm thinking that DartPad could display something like the following when localStorage isn't supported:

**Uh-oh, this embedded DartPad isn't working because your browser has forbidden this site from using local storage. You probably need to use a different browser or enable cookies for this site. More information: [Troubleshooting DartPad](https://dart.dev/tools/dartpad/troubleshoot).**

------------
Or it could be more generic (for any case where you can detect a failure that isn't related to localStorage):

**Uh-oh, this embedded DartPad isn't working. More information: [Troubleshooting DartPad](https://dart.dev/tools/dartpad/troubleshoot).**

------------
I'm not wedded to "uh oh" (which, though I never knew before today, is traditionally spelled with a hyphen), but something like that feels right to me.
