### ISSUE TITLE
[Flutter] Remove need for webOnlyInitilizePlatform() call.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1274]
Right now, in order to get a flutter app to work, you need to make `main() {}` async, and you need to make a call to `await ui.webOnlyInitializePlatform();`.

Ideally, neither of these things should be required, this would put the flutter dartpad more in line with regular flutter apps. 

This would also allow for code samples to be copy-pasted from [api.flutter.dev](api.flutter.dev).

**Comment by johnsonmh** [comment]
If the default template included this, it would make this less of a hassle as well (https://github.com/dart-lang/dart-pad/issues/1276).

**Comment by RedBrogdon** [comment]
This will be done as part of #1282. The current strategy is to copy the Flutter tool's approach and wrap the user's `main` with another one that calls and awaits `ui.webOnlyInitializePlatform()` on the user's behalf prior to running their `main`.

We're already wrapping the user's main in order to hijack the print function and do a couple other things, so this shouldn't be a stretch.

**Comment by RedBrogdon** [comment]
Closing this as a duplicate. #1282 should cover everything here.
