### ISSUE TITLE
[Flutter] Support for projects.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/dart-pad#1290]
I know that this is a big ask, but it would be great to one day have full "projects", with multiple files and even assets in a dartpad. Similar to how codepen has "projects", example: https://codepen.io/waldo/project/editor/DYwanN

This would mean supporting: 

 1. Multiple dart files. They could be nested in directories, but there has to be a top level `main.dart` file with a `main() { ... }` method, this is what the "Run" button will call. 
    *  Making imports work. Local imports would probably be enough and easier, I'm not sure how this would all relate to pub...
 1. Supporting assets. It would be nice to be able to include images in a project and have them render in a Flutter app. Again I'm not sure how this would work with pub and `pubspec.yaml`

**Comment by RedBrogdon** [comment]
These are good suggestions, but they definitely fall into the realm of 2020 planning rather than something we can work on right now.

It's also possible--and this isn't meant as a criticism of your suggestion!--that it might be better to focus on simplicity for DartPad rather than investing in support for larger projects. As Dart and Flutter grow, some of the companies/groups that produce fully featured online IDEs may take an interest and add Flutter support to their tools. This is something we'll need to consider as we figure out our vision for where DartPad goes beyond an updated playground/embeds and Flutter support.

**Comment by johnsonmh** [comment]
@RedBrogdon Totally agreed. This particular feature is essentially crossing the threshold between "live snippet sharing tool" to "web-based IDE". Both are valuable products, but it's a huge product decision that requires a lot of thought/planning to determine what is better to invest in. Thanks for considering this!

**Comment by Luckey-Elijah** [comment]
I think this would be an excellent feature to add. As more Dart and Flutter libraries create extensive documentation (like [`riverpod`](https://riverpod.dev/) and [`bloc`](https://bloclibrary.dev/) for example), those libraries would benefit from demonstrating examples and use cases directly in their documentation websites with project-based DartPads.

I hope adds the potential added value to the Dart/Flutter community. 😄

**Comment by parlough** [comment]
With the [newest iteration](https://github.com/dart-lang/dart-pad/issues/2808) of DartPad, we're focusing on simplicity as RedBrogdon suggested above. As a result, we dropped multi-file support and don't intend to support it in the short term.

For online support of Flutter projects, consider another tool such as [Project IDX](https://idx.dev/) or [Codespaces](https://github.com/features/codespaces). IDX in particular has first-class support for creating Flutter projects :D 

If anyone still feels strongly about DartPad's support for larger projects, please feel free to continue the discussion here or in a new issue. Thanks again!
