### ISSUE TITLE
When trying to edit code it acts like the insert key

### ISSUE THREAD

**Issue by Lincxx** [dart-lang/dart-pad#1435]
*If this was already brought up please close

When trying to edit any code, instead of adding that code, it overwrites it instead. 
eg.  org
class Person {
  String name;
  int age;
}

if I wanted to add full to name, so I would have fullname it does this instead. 
class Person {
  String full;
  int age;
}

Is there a work around or is this an issue?

**Comment by RedBrogdon** [comment]
That's not the expected behavior, nor is it something I've ever seen before.

This is a super basic question, but is it possible your machine was in overtype mode at the time (https://en.wikipedia.org/wiki/Insert_key)?

If not, can you provide some additional information for us? Specifically, I'd like to know:

* What OS and version you were using.
* What browser version you were using.

**Comment by Lincxx** [comment]
Well I went back today and all seems to be working fine. At first I thought I did have the insert key on, but I tried typing and changing in different text editor and I wasn't get that issue. For all I know it could of been a Chrome issue.  Thanks for responding though.

**Comment by RedBrogdon** [comment]
No problem. Glad it's working for you now!
