### ISSUE TITLE
Opening an IndexedDB database fails

### ISSUE THREAD

**Issue by leisim** [dart-lang/dart-pad#1437]
Running the following code in dart-pad fails:

```dart
import 'dart:html';

main() {
  window.indexedDB.open('test');
}
```

The exception:

```
Uncaught Error: Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context.
    at Interceptor.open$1 (<anonymous>:3601:30)
    at Object.main (<anonymous>:2353:36)
    at <anonymous>:3969:9
    at <anonymous>:3953:7
    at dartProgram (<anonymous>:3964:5)
    at <anonymous>:3971:3
    at replaceJavaScript (frame_dark.html:38)
    at messageHandler (frame_dark.html:54)
```

I used `dart2js` to get the javascript code and it runs fine on other online editors (like jsfiddle).

Do you have an idea what might cause this issue?

**Edit:**
I found the reason:

```html
<iframe id="frame" sandbox="allow-scripts" class="flex-auto"></iframe>
```
in [`embed-dart.html`](https://github.com/dart-lang/dart-pad/blob/ab57d1c9d60331cddcf56d1089b3a40d790c0ada/web/embed-dart.html#L149) would need to be 
```html
<iframe id="frame" sandbox="allow-scripts allow-same-origin" class="flex-auto"></iframe>
```

**Comment by RedBrogdon** [comment]
I'm fairly certain this isn't something we'd want to do, though I recognize why someone would want to play with Dart code that accesses IndexedDB.

In general, we don't want the scripts running in our execution iframe to have access to most browser resources or leave any state behind once the user executes something else or closes the browser. This is done primarily for security reasons, but also because it could cause some really weird behaviors (e.g. one DartPad example updates local storage, and suddenly another one won't work unless you crack open the inspector and clear things out).

Also, I believe that putting both `allow-same-origin` and `allow-scripts` on the same iframe allows JS to escape the sandbox and modify the containing page:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox

For those reasons, I'm going to close this as infeasible. If it's particularly important to how you're using DartPad, though, please feel free to come back with additional comments.

**Comment by leisim** [comment]
I wanted to use DartPad in [the Hive documentation](https://newdocs.hivedb.dev/#/tutorials/dark_mode_switch) but I had to fork it anyway to allow importing `hive` and `hive_flutter`.

**Comment by RedBrogdon** [comment]
Yeah, support for pub packages (beyond those that come with the Flutter SDK) is on our roadmap, but also has some security (and performance) concerns that we need to figure out.

Getting your own fork up and running for Hive is a real achievement, so congrats on that. We'd like the codebase to be useful to people beyond our immediate team, so I'm really curious what your experience has been like. Would you be open to getting on a video call with some of the folks from our team?

**Comment by leisim** [comment]
> some security (and performance) concerns that we need to figure out

I understand that. It will be super cool when all the examples and tutorials are not just text but can be tested directly.

> We'd like the codebase to be useful to people beyond our immediate team.

It was fairly straightforward. I removed the `compile` API endpoint and used `compileDDC` for everything because I found it to be much faster. What is the reason to use `dart2js`?

Is there documentation for DDC? If I understood it correctly, it supports incremental compilation so I could precompile Hive and its dependencies.

> Would you be open to getting on a video call with some of the folks from our team?

Sure, I'd love to. How can I reach you?

**Comment by RedBrogdon** [comment]
> What is the reason to use dart2js?

dart2js is the productino compiler, so it produces minified, fast code. It works well for Dart code in DartPad because those snippets have no external dependencies (beyond the core Dart libraries), and are generally small enoug hthat you can compile the whole thing in one go very quickly.

We don't have the option to use dart2js with Flutter, since that compiler would want to compile, analyze, and minify not only the user's code but the entire Flutter SDK as well. That would take a while and result in a large download for each compile. With DDC's incremental compilation features, we can precompile the Flutter and Dart SDKs, link them separately, and then just compile the user's actual code for each request. The browser then puts the pieces together, and can take advantage of browser caching for the Flutter and Dart SDKs, which don't change from request to request.

> Sure, I'd love to. How can I reach you?

Your GitHub account lists `simon.leier@tum.de` as your email address, so I'll try reaching out there.

**Comment by leisim** [comment]
Thanks for the explanation. I'm currently working on a prototype to create a web IDE which will have multi file support and allows using any package.
Each package only needs to be compiled once (using DDC) and can be reused by all projects.

> Your GitHub account lists simon.leier@tum.de as your email address, so I'll try reaching out there.

Please use `simonleier@gmail.com`

**Comment by domesticmouse** [comment]
If your intent is a full IDE, it’d be worth exploring https://github.com/cdr/code-server

I’ve had success in the past getting the flutter VSCode plugin working in `code-server`, which gives you a lot more functionality.

**Comment by leisim** [comment]
Cool thanks, I didn't know code-server, I wanted to implement it using Flutter but I'll take a look :+1:

**Comment by domesticmouse** [comment]
Implementing a code editor in Flutter is definitely an area of interest for us, but there are open questions around the work required to re-implement the rich text editing component. If you are going down that route, please keep us in the loop so we can work together on this. =)

**Comment by leisim** [comment]
> required to re-implement the rich text editing component

Yes, that is the single biggest issue I have. In my opinion there should be a `RichTextField` but there has not been much progress flutter/flutter#12675.
