### ISSUE TITLE
it's different between dartpad and real mechine about ~0

### ISSUE THREAD

**Issue by HannibalKcc** [dart-lang/dart-pad#1448]
```
void main() {
  int zero = 0;
  print(~zero); // dartpad get 4294967295;real mechine and other language (js php) get -1
}
```

**Comment by RedBrogdon** [comment]
What a fascinating bug report. 😄 

The difference in behavior you're seeing here is caused by the different representations of integers in the Dart VM (what you'd see compiling for x86 or ARM) and when compiled to JavaScript.

From the API docs for Dart's int class (emphasis mine):

>When compiling to JavaScript, integers are restricted to values that can be represented exactly by double-precision floating point values. The available integer values include all integers between -2^53 and 2^53, and some integers with larger magnitude. That includes some integers larger than 2^63. ***The behavior of the operators and methods in the int class therefore sometimes differs between the Dart VM and Dart code compiled to JavaScript***. For example, the bitwise operators truncate their operands to 32-bit integers when compiled to JavaScript.

DartPad compiles its users' code into JavaScript, so you see the same results with it as you would with dart2js.
