### ISSUE TITLE
Private attributes

### ISSUE THREAD

**Issue by marcobraghim** [dart-lang/dart-pad#1450]
Everywhere is told that when there is an underscore before the attribute name in Dart so it is considered private. In the following code, even with the underscore, I still can access the _cor attribute outsite of the Class. Why it is happening?

```dart
void main() {
  
  Corola corola = Corola();
  
  print(corola._cor+" Ué");
  
}

class Corola {
  
  String _cor = 'Prata';
  
  int portas = 4;
  
}
```

**Comment by RedBrogdon** [comment]
Olá! Thanks for filing an issue.

Dart has a slightly different concept of privacy than what you find in C++, Java, and many other languages. Rather than being restricted at the class level, private variables and fields are visible only within a single _library_. A Dart package or app can contain several libraries, each of which functions as its own little unit in terms of privacy and namespacing.

When DartPad compiles your code, it considers everything you put in the editor to be part of the same library. That's why the `_cor` field in `Corola` is accessible in your `main` method.

For more information on how privacy, libraries, packages, and so on work in Dart, I recommend this section of the language tour:

https://dart.dev/guides/language/language-tour#libraries-and-visibility

**Comment by marcobraghim** [comment]
Thank you very much.
