### ISSUE TITLE
Private Instance Variables Outside Class in Dart Pad

### ISSUE THREAD

**Issue by Amerkumar** [dart-lang/dart-pad#1463]
I am following the Dart Codelab.Here is the link:  [`Intro to Dart for Java Developer`](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#1)

### Steps to Reproduce this issue:
1. Open Dart Pad.
2. Paste this code. 
```
class Bicycle {
  int cadence;
  int _speed = 0;
  int gear;

  Bicycle(this.cadence, this.gear);

  @override
  String toString() => 'Bicycle : $_speed mph';

  int get speed => _speed;

  void applyBrake(int decrement) => _speed -= decrement;

  void speedUp(int increment) => _speed += increment;
}

void main() {
  var bike = Bicycle(1, 2);
  print(bike);

  bike._speed = 2;
  print(bike);
  
  bike.applyBrake(1);
  print(bike);
}


```
3. Click Run.

### Expected Behaviour:

The Dart Pad must recognise private variable , and should not allow to give it a value in the main function.

Here is the screenshot for further clarification with output. 

![bug](https://user-images.githubusercontent.com/15785087/73165285-57b7bf80-4115-11ea-9d80-fe1936c726a7.png)

**Comment by RedBrogdon** [comment]
This is actually working as intended. You've discovered one of the important differences between how Java and Dart handle privacy. 😄 

Dart has a slightly different concept of privacy than what you find in C++, Java, and many other languages. Rather than being restricted at the class level, private variables and fields are visible only within a single library. A Dart package or app can contain several libraries, each of which functions as its own little unit in terms of privacy and namespacing.

When DartPad compiles your code, it considers everything you put in the editor to be part of the same library. That's why the _speed field in Bicycle is accessible in your main method.

For more information on how privacy, libraries, packages, and so on work in Dart, I recommend this section of the language tour:

https://dart.dev/guides/language/language-tour#libraries-and-visibility
