### ISSUE TITLE
Add line number

### ISSUE THREAD

**Issue by nicolasdupere** [dart-lang/dart-pad#1465]
When I have a problem with my code, it's really quicker to look at the number of the line of code on the left (if there was one) instead of trying to find the wrong code with an underlined color.
![line](https://user-images.githubusercontent.com/6632583/73459886-97fd8480-4345-11ea-971c-9c7971c7716a.jpg)

**Comment by RedBrogdon** [comment]
We've had an open issue for this a while now, #317. So far we haven't been able to find time to get it done, but we're hearing about it more and more, so that will likely change.

I'm going to close this as a dupe. We'll keep it in mind as more user interest in that feature, though, so thanks for filing it.
