### ISSUE TITLE
CommonServer failing to restart/recover correctly

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1468]
Certain instances of the backend are entering into a state in which one or more analysis servers have failed and the system is unable to correctly restart them when restarting CommonServer. This causes the instance to return 500s for any requests dependent on the analysis server (docs, format, analyze, etc). This continues until the instance is recycled.

The last time the analysis server code was significantly changed was during last year's addition of Flutter, so it's possible some bug was introduced there that only manifests occasionally.

**Comment by domesticmouse** [comment]
/cc @devoncarew you were asking about a bug for tracking the analysis servers crashing. Turns out, @RedBrogdon raised one.

I believe the Cloud Run infra will automatically decomission a server that returns a couple of 500s in a row, and looking at the logs we get sporadic 500s, but not the outages we suffered on AppEngine Flex back in the day.

**Comment by domesticmouse** [comment]
Closing this out now that Dart Services only runs on Cloud Run
