### ISSUE TITLE
General dartpad performance - Flutter API docs

### ISSUE THREAD

**Issue by GaryQian** [dart-lang/dart-pad#1483]
This bug describes Flutter's use case for improved performance.

We have noticed that the addition of dartpad to Flutter API docs has resulted in a noticeably slower page.

For some surface level metrics, With dartpad: [speedtest](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmaster-api.flutter.dev%2Fflutter%2Fmaterial%2FScaffold-class.html&tab=desktop) vs without dartpad: [speedtest](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fapi.flutter.dev%2Fflutter%2Fmaterial%2FScaffold-class.html&tab=desktop)

We have seen through surveys on the docs that there are a subset of users who are already complaining that the old dartpad-less docs are too slow/memory heavy, which causes concern that the addition of dartpad would increase performance requirements to the point of a non-insignificant chunk of people to be unable to use the API docs.

Some areas we have noticed slowdown:

- Memory
- Initial download
- FPS
- responsiveness

**Comment by parlough** [comment]
Thanks for the issue and details!

DartPad has evolved a lot since then and we have a few newer issues tracking specific performance concerns, so I'll close this in favor of those. Feel free to open other more specific issues too.

The largest performance issues for the API docs occurs multiple embedded DartPads, which likely won't be solved until multi-view support lands in Flutter.
