### ISSUE TITLE
dart-services does not compile Dart when run on Windows

### ISSUE THREAD

**Issue by liudonghua123** [dart-lang/dart-pad#1493]
I read the README and the related https://github.com/dart-lang/dart-services project. But still could not found how can I start it locally on my own computer. Due to my network issues, I want to run it locally, Can we build a docker container which all the staffs are in it, and run more easier for beginners?

**Comment by RedBrogdon** [comment]
Both projects should work locally. We generally run them only on Linux and macOS machines, though, so there might be some occasional issues found on that OS.

Most of us run and test the site with [grinder](https://pub.dev/packages/grinder). You can see the grind file at `/tool/grind.dart`, which lists the available tasks.

If you've got a specific error message or crash that you're seeing, post it here, and we can try to work through it.

**Comment by liudonghua123** [comment]
@RedBrogdon Now I could run the frontend via `grind serve-custom-backend`, but I need to add cmd extension of the vulcanize runSync in grind.dart on Windows platform. The final code like the following.
```dart
vulcanize(String filepath) {
  var htmlFile = _buildDir.join(filepath);
  log('${htmlFile.path} original: ${_printSize(htmlFile)}');
  var result = Process.runSync(
      // changed from vulcanize to vulcanize.cmd due Process.run ignore the Windows PATHEXT issue
      'vulcanize.cmd',
      [
......
```

After I also started the backend via `dart bin/server_dev.dart --port 8082`, I run the hello world code in browser, but I got the errors shown in the following picture.

![image](https://user-images.githubusercontent.com/2276718/75862434-eb2d9000-5e39-11ea-8175-46a06349193d.png)

I thinks it is the same as https://github.com/dart-lang/sdk/issues/31291。
> I think Process.run/Process.runSync should consider the PATHEXT environment. And run without executable extension.

**Comment by liudonghua123** [comment]
Later I tried the same steps on Linux, no such problems appeared. 
Hope the dart/dart-pad team can go through the root sources to fix this strange problem.

**Comment by RedBrogdon** [comment]
Thanks for the extra info. I've updated the title of this issue to reflect that it's a Windows-related problem.

**Comment by domesticmouse** [comment]
Ok, I have spent a couple of days digging into this issue, as evidenced by https://github.com/dart-lang/dart-services/pull/490 and https://github.com/dart-lang/dart-services/pull/491

While fixing low hanging fruit of path handling is pretty easy, there are some deep issues with how we handle invoking the compilation chains that are beyond my skill set to fix.

About now I need to remind everyone of an insight from the Chrome team - what ever isn't tested, is by definition broken, eventually. The only supported platform for Dart Services is Linux, because that is where we run our travis tests, and that is where we deploy. It also works on macOS, because Linux and macOS are both Unix variants.

Windows is another kettle of fish. We can choose to make it a supported platform, sinking engineering time into making it work, and keeping it working. However doing so will come at a direct cost of not being able to implement #901, which I suspect is a much higher priority than supporting MS Windows as a deployment target.

**Comment by domesticmouse** [comment]
Sorry @liudonghua123, we have made the call that supporting MS Windows as a deploy target isn't a priority at this point.
