### ISSUE TITLE
Should show warning when trying to modify "const" var

### ISSUE THREAD

**Issue by jaxlogan** [dart-lang/dart-pad#1512]
DartPad should show some kind of warning/error when trying to mutate a "const" declared value, such as:

```
const array = ["friend1", "friend2"];

void main() {
  print(array);
  array.add("friend3");
  print(array);                  // Warning/compiler error here
}
```

**Comment by RedBrogdon** [comment]
Thanks for filing an issue!

Running this code in my browser is producing this error:

```
[friend1, friend2]
Uncaught Error: Unsupported operation: add
```

Is that different from what you have been seeing?

**Comment by jaxlogan** [comment]
Hi!

At DartPad, I was not able to see any error message. Perhaps it was my browser, although I was using a Chromium based one.

**Comment by eernstg** [comment]
With respect to proposals for language support for statically known immutability, you could take a look at https://github.com/dart-lang/language/issues/125 and https://github.com/dart-lang/language/issues/314.

We don't have that, yet. For now it is a purely dynamic property that some collections are unmodifiable. This includes the ones that are obtained by evaluating a constant expression, as in your example.

So that's the reason why you do _not_ get an error/warning at compile time for `array.add("friend3");`, but you _do_ get an exception at run time.

I'll close this issue: Dartpad behaves as expected, and getting a compile-time error message rather than a run-time exception is a request for a language enhancement which should be discussed in the issues in the language repository like the ones mentioned above.
