### ISSUE TITLE
Firefox Dartpad not displaying the output correctly

### ISSUE THREAD

**Issue by moizahmed97** [dart-lang/dart-pad#1515]
When using the property mainAxisAlignment firefox does not register the change, while chrome does 
Here the mainAxisAlignment property is set to end but Firefox does not move the containers to the end as it does in Chrome

![image](https://user-images.githubusercontent.com/44170860/77517238-d7030e80-6e8c-11ea-9d09-369fe221d234.png)

**Comment by RedBrogdon** [comment]
I believe the issue here is that the code is setting mainAxisSize to `MainAxisSize.min`. That causes the row to take up as little space as possible (it "shrink-wraps" its children), which leaves extra room. At that point, the mainAxisAlignment property doesn't have an effect -- the children are aligned with both ends of the Row, since it's exactly their size.

Try removing the mainAxisSize and running it again. This is what I'm seeing in Firefox in that case:

![image](https://user-images.githubusercontent.com/969662/77568718-4cb7ac00-6e86-11ea-9461-ba954b01d653.png)
