### ISSUE TITLE
Investigate if POST to /version can be dropped

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/dart-pad#1539]
Context: https://github.com/dart-lang/dart-services/pull/488#discussion_r411772463

**Comment by johnpryan** [comment]
I think this can be a GET request instead

**Comment by domesticmouse** [comment]
The backend currently supports both `GET` and `POST` to `/version`. This is a tracking bug to see if I can just turn off POST or if I break stuff in doing that. It’s probably a NOP, but I’d prefer to make sure. 😎

**Comment by johnpryan** [comment]
gotcha, the front-end still uses POST I think

**Comment by domesticmouse** [comment]
> gotcha, the front-end still uses POST I think

@RedBrogdon I think that'd be stalemate, yeah?

**Comment by domesticmouse** [comment]
Confirmed, DartPad.dev is requesting https://dart-services.appspot.com/api/dartservices/v2/version
via a POST request. 

Closing out.

**Comment by RedBrogdon** [comment]
Yeah, I just took a spin through the code, and all requests go through the same base method, which uses POST for everything. I imagine this is an artifact of the design pattern used for the discoveryapis code.

We could certainly rework the front-end to use GET (since it should, IMHO), but since you've already got the backend supporting POST, I don't see much reason to bother.

**Comment by RedBrogdon** [comment]
> Closing out.

Well, that'll teach my to leave my GitHub tabs open for four hours before coming back to finish a comment.
