### ISSUE TITLE
No documentation to install dartpad on local environment

### ISSUE THREAD

**Issue by CodingEarth** [dart-lang/dart-pad#1542]
No documentation has been provided to install dartpad on local environment

Environment : Windows/Linux

**Comment by domesticmouse** [comment]
Hi @CodingEarth,

I'm curious what you are attempting to do here. While running both the server (`dart-services`) and the client (`dart-pad`) locally is currently supported for development workflows, it isn't the primary focus.

Depending on your use case, the [Embedding API](https://github.com/dart-lang/dart-pad/wiki/Embedding-Guide) is probably where I'd suggest starting.

**Comment by rosera** [comment]
+1 looking at hosting dartpad. Unable to use embedded solution did to company security restrictions. Would be useful to understand how to build the platform from scratch.

**Comment by domesticmouse** [comment]
The compilation backend `dart-services` is a Docker image. The default build depends on AppEngine's APIs, but the development build does not. If you look at https://github.com/dart-lang/dart-services/blob/master/Dockerfile.cloud_run you can see a docker image recipe that works on Cloud Run, and should run pretty much anywhere.

The front end uses GitHub gists for the sample code. I suspect that would be a no-go for pretty much any security in house solution, as gists are public.

I'd ask y'all to elucidate your requirements in more detail, because DartPad isn't going to be easily converted into something other than a publically accessible training utility. It isn't on our roadmap, given our limited engineering resources.

**Comment by RedBrogdon** [comment]
As @domesticmouse mentioned, dart-services is set up in such a way that one should be able to run its Docker image just about anywhere. We don't have a ton of engineering bandwidth, though, and have chosen to prioritize bugs and feature development over additional documentation and refinement of the setup process.

That said, if you do go ahead with running dart-pad and dart-services locally, we'd love to incorporate anything you learn into our docs, so don't be shy!

**Comment by osaxma** [comment]
For reference, the link that @domesticmouse shared has changed to:

https://github.com/dart-lang/dart-services/blob/master/cloud_run.Dockerfile
