### ISSUE TITLE
Feature request: Add a "Download as Flutter Project" button

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/dart-pad#1550]
We've gotten a Q2 feature request to add a button to DartPad's UI (could be a menu option in the embed) that will allow users to download their current Flutter code as a Flutter project that can be run from the command line, opened in an IDE, and so on.

This would likely involve:

* Adding new capability to FlutterWebManager:
  - Run `flutter create dartpad_project` in a directory somewhere
* Adding a new POST method to the API that accepts user code and:
  - Copies that code into the premade project
  - Zips the result
  - Sends it down as the response.
* Adding UI to dart-pad to invoke the method.

Some wrinkles:

* DardPad currently uses the dev branch of Flutter (soon to be the beta branch), but this could cause user confusion if they need to switch channels to use the project.
* Do we care if the user's code is broken at the time they hit the button?
* Should the code be formatted on behalf of the user?
* ...are there more?

**Comment by devoncarew** [comment]
Some more notes:

- without the complexity of flutter projects, this is likely just creating a well-formed zip file with a few contained files (a dart file, a pubspec, perhaps an analysis options file, a readme.md, and potentially some IDE metadata files)
- flutter does complicate this (but it likely a driving use case)
- we can help in terms of defining any potential IDE metadata (which files would help the user get quickly bootstrapped in an IDE)

**Comment by domesticmouse** [comment]
`dart-services` is now on `flutter channel beta`, which seems like a more sane choice since it is now embedded in the API docs.

I'd suggest for flutter code that we use `flutter create` from beta (so it has the web runner directory) as our baseline project, and for Dart I'd suggest we take `stagehand`'s console full template.

I don't think beta/stable will be too much of an issue, and it's a better getting started experience for it to "mostly work" with a stable download, rather than hard failing by setting the flutter minimum to current beta and having a user with stable download wondering how to fix it.

Apologies for the rambling brain dump, it's way too early in the morning here, but this sounds like a very useful feature.

**Comment by parlough** [comment]
Closing as the new UI supports a similar "Open in IDX" button and we're looking to refresh the issue tracker. If anyone would still like to see that expanded to downloading a ZIP, please open a new issue. Thanks so much!
