### ISSUE TITLE
Dart pad - No fault detection

### ISSUE THREAD

**Issue by bshlomo** [dart-lang/dart-pad#1551]
This code in the dartPad not working well, it should report an error

```dart
class TagTable {
  static  Map<String, List<String>> records = const {
    'RCRD_ALL': ['key1', 'key2'],
  };
}

void main() {
  print('1-${TagTable.records}');

  TagTable.records['RCRD_ALL'] = ['key5', 'key6'];

  print('2-${TagTable.records}');
}
```

--

Win-7 - Microsoft Windows [Version 6.1.7601]
Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "windows_x64"

**Comment by mit-mit** [comment]
cc @RedBrogdon @domesticmouse

**Comment by RedBrogdon** [comment]
I'm seeing an error when this is run:

![image](https://user-images.githubusercontent.com/969662/81243192-fdf04c80-8fc3-11ea-8acc-8653c420ea0c.png)

There is now analyzer error when running this code, which is perhaps the source of confusion. I'm going to go ahead and close this, since DartPad is matching the behavior of a command line dartanalyzer call.

I can't for the life of me remember why this isn't caught as a static analysis issue, but I know there's a reason for it. If someone from the Dart team can provide more info, I'd be much obliged. 😄

**Comment by bshlomo** [comment]
I checked it with Dart 2.8.1, and I got the same result as 
noted by @RedBrogdon   
![1551](https://user-images.githubusercontent.com/42788959/81259036-b6a7a180-903f-11ea-92f1-00f11196833e.png)
Thank you

**Comment by eernstg** [comment]
@RedBrogdon wrote:
> I can't for the life of me remember why this isn't caught as a static analysis issue

There are several proposals about adding improved support for immutable entities in Dart (e.g., several of the ideas presented in dart-lang/language#314), but it was initially a property that has no representation in the types of objects.

For example, an unmodifiable list can be created using the constructor `List.unmodifiable` (so the new object has static type `List<...>`, just like the modifiable ones). Similarly, `const <SomeType>[some, elements]` has static type `List<...>`, and the type system has no idea which lists are mutable and which ones are not.

It's not hard to declare a class whose instances are immutable, say, 

```dart
class Point {
  final int x,y;
  Point(this.x, this.y);
}
```

but, for historical reasons, standard data structures in Dart don't do this. Also, we'd need some additional convenience features (like auto-generated deep equality and hashCode) in order to make immutable classes work well.

So I guess the reason why there is no compile-time error for modifying a constant list/map/set is best described as "history". ;)
