### ISSUE TITLE
Convenience in pasting urls (url rewrite)

### ISSUE THREAD

**Issue by jaggzh** [dart-lang/dart-pad#1565]
How about we allow rewriting a URL:
https://dartpad.dev/https://gist.github.com/{user}/{gist_id}
-> The normal dartpad gist url. :)

Copying and pasting a URL is much easier than going to manually select the gist id (and can, usually, readily and quickly be done with two keyboard commands).

**Comment by RedBrogdon** [comment]
I'm not sure I think this would be a good feature. While everyone's different, I've never had an issue double-clicking on the Gist ID in a GitHub URL to select it and then copying.

There would also be the extra work of additional parsing and route-handling in our front end, and we'd be coupling ourselves to a particular host/domain rather than just the Gist ID.

If anyone feels particularly strongly about this, they're free to add comments. I'm going to go ahead and close the issue for now, though.
