### ISSUE TITLE
Script error for flutter examples on ipad / safari or chrome

### ISSUE THREAD

**Issue by unoctanium** [dart-lang/dart-pad#1566]
## What happened?
 
On dartpad.dev, I can run dart examples on ipad with ipados 13.4.1, but I Can‘t run flutter examples.

Flutter code shows console error : „Script error“, when Pressing run and then tapping in the app pane. App does not react.

## Steps to reproduce problem

Open safari on ipad, browse to https://dartpad.dev, select samples / counter, press run, press plus-button in the counter app

Result: Button tool tip („Increment“) shows up. Button does not increment counter, console shows script error.

### Browser

Browser:
Safari on ipados 13.4.1. 
same result with newest chrome on ipad

**Comment by unoctanium** [comment]
Counter app works with firefox on ios.
Counter counts if plus button is pressend.

Bur even With Firefox there are script errors. Here, 3 script errors per button or scree tap(press)

**Comment by RedBrogdon** [comment]
Thanks for filing an issue. We're not always able to test on every device, so this is helpful.

Can you tell me what errors appear in the logs when you connect web inspector to the instance of Safari on device?

**Comment by devnoaman** [comment]
hi @RedBrogdon , i  faced the same error and when i start the inspector i get these errors.

`[Error] Resource blocked by content blocker
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:333)
	(anonymous function) (analytics.js:38:480)
[Error] XMLHttpRequest cannot load https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-26406144-18&cid=1423237509.1633080647&jid=405463725&gjid=906746617&_gid=516873637.1633183263&_u=QACAAEAAAAAAAC~&z=988495471 due to access control checks.
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:333)
	(anonymous function) (analytics.js:38:480)
[Error] Resource blocked by content blocker
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] XMLHttpRequest cannot load https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-26406144-18&cid=1423237509.1633080647&jid=876318979&gjid=2065474913&_gid=516873637.1633183263&_u=SACAAEABAAAAAC~&z=1221366208 due to access control checks.
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] Error
	throw_ (dart_sdk.js:5061)
	assertFailed (dart_sdk.js:4986)
	_shouldMarkStateDirty (flutter_web.js:439767:113)
	updateWithEvent (flutter_web.js:439803)
	dispatchEvent (flutter_web.js:333399)
	(anonymous function) (flutter_web.js:332139)
	handlePointerEvent (flutter_web.js:332113)
	(anonymous function) (flutter_web.js:332103)
	(anonymous function) (flutter_web.js:332094)
	[_handlePointerDataPacket]
	invoke1 (dart_sdk.js:179667)
	invokeOnPointerDataPacket (dart_sdk.js:160119)
	(anonymous function) (dart_sdk.js:160965)
	[_onPointerData]
	(anonymous function) (dart_sdk.js:161373)
	loggedHandler (dart_sdk.js:161058)
[Error] Error
	throw_ (dart_sdk.js:5061)
	assertFailed (dart_sdk.js:4986)
	_shouldMarkStateDirty (flutter_web.js:439767:113)
	updateWithEvent (flutter_web.js:439803)
	dispatchEvent (flutter_web.js:333399)
	(anonymous function) (flutter_web.js:332139)
	handlePointerEvent (flutter_web.js:332113)
	(anonymous function) (flutter_web.js:332103)
	(anonymous function) (flutter_web.js:332094)
	[_handlePointerDataPacket]
	invoke1 (dart_sdk.js:179667)
	invokeOnPointerDataPacket (dart_sdk.js:160119)
	(anonymous function) (dart_sdk.js:160965)
	[_onPointerData]
	(anonymous function) (dart_sdk.js:161373)
	loggedHandler (dart_sdk.js:161058)
[Error] Resource blocked by content blocker
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] XMLHttpRequest cannot load https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-26406144-18&cid=1423237509.1633080647&jid=40653281&gjid=149956550&_gid=516873637.1633183263&_u=SACAAEABAAAAAC~&z=381068571 due to access control checks.
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] Error
	throw_ (dart_sdk.js:5061)
	assertFailed (dart_sdk.js:4986)
	_shouldMarkStateDirty (flutter_web.js:439767:113)
	updateWithEvent (flutter_web.js:439803)
	dispatchEvent (flutter_web.js:333399)
	(anonymous function) (flutter_web.js:332139)
	handlePointerEvent (flutter_web.js:332113)
	(anonymous function) (flutter_web.js:332103)
	(anonymous function) (flutter_web.js:332094)
	[_handlePointerDataPacket]
	invoke1 (dart_sdk.js:179667)
	invokeOnPointerDataPacket (dart_sdk.js:160119)
	(anonymous function) (dart_sdk.js:160965)
	[_onPointerData]
	(anonymous function) (dart_sdk.js:161373)
	loggedHandler (dart_sdk.js:161058)
[Error] Resource blocked by content blocker
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] XMLHttpRequest cannot load https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-26406144-18&cid=1423237509.1633080647&jid=1830377005&gjid=353871199&_gid=516873637.1633183263&_u=SACAAEABAAAAAC~&z=276460567 due to access control checks.
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] Error
	throw_ (dart_sdk.js:5061)
	assertFailed (dart_sdk.js:4986)
	_shouldMarkStateDirty (flutter_web.js:439767:113)
	updateWithEvent (flutter_web.js:439803)
	dispatchEvent (flutter_web.js:333399)
	(anonymous function) (flutter_web.js:332139)
	handlePointerEvent (flutter_web.js:332113)
	(anonymous function) (flutter_web.js:332103)
	(anonymous function) (flutter_web.js:332094)
	[_handlePointerDataPacket]
	invoke1 (dart_sdk.js:179667)
	invokeOnPointerDataPacket (dart_sdk.js:160119)
	(anonymous function) (dart_sdk.js:160965)
	[_onPointerData]
	(anonymous function) (dart_sdk.js:161373)
	loggedHandler (dart_sdk.js:161058)
> Selected Element
< <textarea style="position: absolute; bottom: -1em; padding: 0px; width: 1000px; height: 1em; outline: none;" autocorrect="off" autocapitalize="off" spellcheck="false" tabindex="0">…</textarea>
[Error] Failed to load resource: the server responded with a status of 404 () (split.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (main.dart.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (playground.dart.js.map, line 0)`

**Comment by devnoaman** [comment]
hi @RedBrogdon , i faced the same error and when i start the inspector i get these errors.

**Comment by devnoaman** [comment]
> [Error] Resource blocked by content blocker
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:333)
	(anonymous function) (analytics.js:38:480)
[Error] XMLHttpRequest cannot load https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-26406144-18&cid=1423237509.1633080647&jid=405463725&gjid=906746617&_gid=516873637.1633183263&_u=QACAAEAAAAAAAC~&z=988495471 due to access control checks.
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:333)
	(anonymous function) (analytics.js:38:480)
[Error] Resource blocked by content blocker
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] XMLHttpRequest cannot load https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-26406144-18&cid=1423237509.1633080647&jid=876318979&gjid=2065474913&_gid=516873637.1633183263&_u=SACAAEABAAAAAC~&z=1221366208 due to access control checks.
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] Error
	throw_ (dart_sdk.js:5061)
	assertFailed (dart_sdk.js:4986)
	_shouldMarkStateDirty (flutter_web.js:439767:113)
	updateWithEvent (flutter_web.js:439803)
	dispatchEvent (flutter_web.js:333399)
	(anonymous function) (flutter_web.js:332139)
	handlePointerEvent (flutter_web.js:332113)
	(anonymous function) (flutter_web.js:332103)
	(anonymous function) (flutter_web.js:332094)
	[_handlePointerDataPacket]
	invoke1 (dart_sdk.js:179667)
	invokeOnPointerDataPacket (dart_sdk.js:160119)
	(anonymous function) (dart_sdk.js:160965)
	[_onPointerData]
	(anonymous function) (dart_sdk.js:161373)
	loggedHandler (dart_sdk.js:161058)
[Error] Error
	throw_ (dart_sdk.js:5061)
	assertFailed (dart_sdk.js:4986)
	_shouldMarkStateDirty (flutter_web.js:439767:113)
	updateWithEvent (flutter_web.js:439803)
	dispatchEvent (flutter_web.js:333399)
	(anonymous function) (flutter_web.js:332139)
	handlePointerEvent (flutter_web.js:332113)
	(anonymous function) (flutter_web.js:332103)
	(anonymous function) (flutter_web.js:332094)
	[_handlePointerDataPacket]
	invoke1 (dart_sdk.js:179667)
	invokeOnPointerDataPacket (dart_sdk.js:160119)
	(anonymous function) (dart_sdk.js:160965)
	[_onPointerData]
	(anonymous function) (dart_sdk.js:161373)
	loggedHandler (dart_sdk.js:161058)
[Error] Resource blocked by content blocker
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] XMLHttpRequest cannot load https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-26406144-18&cid=1423237509.1633080647&jid=40653281&gjid=149956550&_gid=516873637.1633183263&_u=SACAAEABAAAAAC~&z=381068571 due to access control checks.
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] Error
	throw_ (dart_sdk.js:5061)
	assertFailed (dart_sdk.js:4986)
	_shouldMarkStateDirty (flutter_web.js:439767:113)
	updateWithEvent (flutter_web.js:439803)
	dispatchEvent (flutter_web.js:333399)
	(anonymous function) (flutter_web.js:332139)
	handlePointerEvent (flutter_web.js:332113)
	(anonymous function) (flutter_web.js:332103)
	(anonymous function) (flutter_web.js:332094)
	[_handlePointerDataPacket]
	invoke1 (dart_sdk.js:179667)
	invokeOnPointerDataPacket (dart_sdk.js:160119)
	(anonymous function) (dart_sdk.js:160965)
	[_onPointerData]
	(anonymous function) (dart_sdk.js:161373)
	loggedHandler (dart_sdk.js:161058)
[Error] Resource blocked by content blocker
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] XMLHttpRequest cannot load https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j93&tid=UA-26406144-18&cid=1423237509.1633080647&jid=1830377005&gjid=353871199&_gid=516873637.1633183263&_u=SACAAEABAAAAAC~&z=276460567 due to access control checks.
	wd (analytics.js:39)
	pe (analytics.js:38)
	oc (analytics.js:39:471)
	Ea (analytics.js:39:195)
	(anonymous function) (analytics.js:38:480)
[Error] Error
	throw_ (dart_sdk.js:5061)
	assertFailed (dart_sdk.js:4986)
	_shouldMarkStateDirty (flutter_web.js:439767:113)
	updateWithEvent (flutter_web.js:439803)
	dispatchEvent (flutter_web.js:333399)
	(anonymous function) (flutter_web.js:332139)
	handlePointerEvent (flutter_web.js:332113)
	(anonymous function) (flutter_web.js:332103)
	(anonymous function) (flutter_web.js:332094)
	[_handlePointerDataPacket]
	invoke1 (dart_sdk.js:179667)
	invokeOnPointerDataPacket (dart_sdk.js:160119)
	(anonymous function) (dart_sdk.js:160965)
	[_onPointerData]
	(anonymous function) (dart_sdk.js:161373)
	loggedHandler (dart_sdk.js:161058)

**Comment by devnoaman** [comment]
in addition:

> [Error] Failed to load resource: the server responded with a status of 404 () (split.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (main.dart.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (playground.dart.js.map, line 0)

**Comment by devnoaman** [comment]
please @RedBrogdon check them out .
