### ISSUE TITLE
Using image assets in CustomPainter

### ISSUE THREAD

**Issue by camillo777** [dart-lang/dart-pad#1568]
Is there a way to import image assets into DartPad to be used with CustomPainter?

**Comment by RedBrogdon** [comment]
DartPad doesn't have a way to serve assets in the same way a "real" Flutter app would. We're unlikely to implement one, since it would involve setting up some kind of storage backend, which is a complexity we'd prefer to avoid.

You can totally grab images from the network, though, if you have a place to make them available ([Firebase hosting](https://firebase.google.com/docs/hosting), for example). See [NetworkImage](https://api.flutter.dev/flutter/painting/NetworkImage-class.html) for details.
