### ISSUE TITLE
DartPad not using Null Safe SDK?

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart-pad#1582]
Example:
```dart
List<int> x = <int>[1].map((x) => x);
```
gives the error:
```
A value of type 'Iterable<int*>*' can't be assigned to a variable of type 'List<int>' - line 1
```

This suggests that the DartPad analyzer is not using the Null Safe SDK.

**Comment by mit-mit** [comment]
cc @RedBrogdon

**Comment by RedBrogdon** [comment]
The analyzer certainly knows some things about null safety; otherwise the snippets wouldn't work:

https://nullsafety.dartpad.dev/3d9c1769de7912c654bc5d132aff60ac

It seems like it's getting confused sometimes and treating core libraries as if they were legacy versions, though. #1569 has the same issue with docs.

**Comment by RedBrogdon** [comment]
This has been corrected in today's release:

![image](https://user-images.githubusercontent.com/969662/90300332-de807f80-de4e-11ea-82bd-3dd089c4e823.png)

The analyzer is no longer confused about legacy types and inserting asterisks into things.
