### ISSUE TITLE
How to run localserver

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart-pad#1602]
`grind server` -> local web server works, but when i switch 

```
// final serverURLs = [
//   'https://dart-services.appspot.com/',
//   'https://dart-services-0.appspot.com/',
// ];

// A set of URLs to use while debugging.
final serverURLs = [
  'http://127.0.0.1:8082/',
];
```

web to point localhost (in `common.dart`), it seems to be not working.

how can i run compiler server locally?

additionally is there a way to run with --watch option? like common web development.

**Comment by domesticmouse** [comment]
Unfortunately `dart-services` isn't built for hot-reload based development. It is basically a thin wrapper around the Dart and Flutter SDKs, designed for supporting [DartPad.dev](https://dartpad.dev/).

I'm curious what your use case is?

**Comment by softmarshmallow** [comment]
Thanks for the reply. i'm just playing around it, figuring out how it works -- editing and see whats changing.  : )

**Comment by domesticmouse** [comment]
In which case, don't be shy about asking questions, either here or @domesticmouse on twitter. =)

Btw, for running the server locally `grind serve` for `dart-services` and there is a `grind` target for `dart-pad` that allows you to re-write the target backend. 

Right now the target rewrite for `dart-pad` is broken because of the round robin code, but that is being tracked in https://github.com/dart-lang/dart-pad/issues/1591

Closing this out for now, but please feel free to keep asking questions!
