### ISSUE TITLE
Window size of editor suddenly becomes half the width.

### ISSUE THREAD

**Issue by karan-ta** [dart-lang/dart-pad#1634]
## What happened?

Window size width becomes half suddenly as if the window is falling.
Without me doing anything strange.
I ma just reading coding or selecting code and width becomes half.

## Steps to reproduce problem
Occurs randomly

### Browser

Browser:
Chrome.

Version:

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system:fedora 26

Version:

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:
Any code.
```
// Paste code here.
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
[paste console output here]
```

If you were running Flutter code, you can also paste an image of the
Flutter output directly into this bug report.

**Comment by RedBrogdon** [comment]
That's certainly not the experience we're looking for. Can you provide some additional information (it will be very hard to replicate the issue and fix it otherwise)?

* What code was in the editor when this happened?
* Were there any errors in the browser's JavaScript console?
* Have you seen the same behavior in any other browser?
