### ISSUE TITLE
Display argument names during completion

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#172]
@kasperpeulen for your consideration:

When performing a completion which takes arguments, the argument list should be displayed in the area where the completion was as a smaller entry

So for example after print has been selected, the when the cursor is inside the ()

the "Object object" part of the completion should be made bold

![image](https://cloud.githubusercontent.com/assets/2978182/6822303/a2aa6b08-d2d6-11e4-8fc5-930f960236d0.png)

If there are multiple arguments, the one that is currently edited should be bold. 

This allows people to not forget what they need in order to use a method.

**Comment by kasperpeulen** [comment]
@lukechurch I'm not completely sure how to make this look. I guess we don't want regular autocompletion there, in the sense that pressing enter shouldn't autocomplete ?

![image](https://cloud.githubusercontent.com/assets/1035299/6824463/c925eaac-d2f2-11e4-9c6b-abcda3145413.png)

Maybe something like this ?

**Comment by lukechurch** [comment]
yeah, something like that would be great for now, though soon I'd like to have completions suggesting possible argument completions as well. 

We could also put it above the code being edited to make it more clearly separated from the completion UI, though in general I'd prefer it to stay below so we can use the space above for other purposes.

**Comment by kasperpeulen** [comment]
It seems quite hard to do this nicely. I've been looking at how dart editor and webstorm does this. Webstorm is really buggy. I'm not sure if I understand it correctly, but otherwise it doesn't seem to work 90% of the time.

Dart editor does it quite fine, but I think the main problem is, to determine when this parameter popup should be triggered. Dart editor mechanism seems to be something like:

`if (completionInserted && completion.isMethod) then {show parameterinfo}`

But as the mechanism is so bound to the completion, in many othere  cases it won't work:

![](http://i.imgur.com/xgJN3QX.gif)

For the documentation panel PR, I request documentation info after any keystroke. We could maybe also use that information to determine if the user is editing parameters. Something like:

if ( cursor is inside parenthesis && right before parenthesis there is a method name) then { display parameter info of method }

**Comment by kasperpeulen** [comment]
Something like this could work I think:
@lukechurch 
https://dartpad.dartlang.org/b7660a189e5cd4cc38a4

**Comment by kasperpeulen** [comment]
@lukechurch I think this patch https://github.com/dart-lang/dart-services/pull/91 would be useful for fixing this issue.

**Comment by kasperpeulen** [comment]
It is probably better to do this with a popup, but this was a little bit easier, and at least it is working:
![](http://g.recordit.co/n3WpW6dfwB.gif)

I couldn't test the completion when running the dart services locally, so this is just a beginning. What do you guys think, making a popup ? And when should it be triggered ?

**Comment by devoncarew** [comment]
I think this is best with a popup. I assume we'd want to trigger it the same as for code completion; I'm not sure how we'd discriminate between completing the params for the call vs. completing some aspect of a param. We may be able to lean on the analysis server for this?

@kasperpeulen, I'm a bit worried that you might spend a lot of time writing code in a particular direction, which might not be exactly how Luke or I would envision something ourselves. It's probably best to sketch out ideas in a github issue first before writing a lot of code. Your contributions have been extremely valuable! I want to make sure you don't get frustrated by having a large arc of work not be accepted.

**Comment by kasperpeulen** [comment]
@devoncarew Oh, I do spent a lot of time on it, but that is not really because it so much code, but more because I still have have to learn a lot about the dart language, and web programming in general. For me this is really a learning experience and even if you don't merge it, I learn a lot.

I wrote a couple of PR for the dart plugin of webstorm, and there it took several weeks before it got reviewed and some rejected. You guys react extremely fast, so that it makes already a lot more fun, even if you decide to not merge it. :)

But ok, skechting the idea beforehand will never hurt. I do think making it a popup is a good idea, but it is bit more difficult. For example how do I find the x,y coordinates of the caret ? 

This is my latest latest try:
![](http://i.imgur.com/tUqXs12.gif)

Maybe codemirror has some method to find the x,y coordinates of the caret ?

> I assume we'd want to trigger it the same as for code completion; I'm not sure how we'd discriminate between completing the params for the call vs. completing some aspect of a param.

Dart editor seem to put the parameter info above and the completion info below. Do you think we should it trigger only on ctrl+enter ? I feel like we should trigger it whenever there is parameter info available. 

Maybe request if there is parameter info in the following cases:

* the users presses `(`
* the users completes a method or function using the completion popup
* navigation keys and only request for parameter info if the cursor is inside parenthesis for example `(text<caret>)`
* if the parameter info is active, update when the user presses `,`

**Comment by lukechurch** [comment]
>the users presses (
the users completes a method or function using the completion popup
navigation keys and only request for parameter info if the cursor is inside parenthesis for example (text<caret>)
if the parameter info is active, update when the user presses ,

I agree with these as a first cut. In a recent user study on code completion we saw that people were often having to delete a method call and bring it back again only to get to see these argument name lists.

**Comment by devoncarew** [comment]
That param popup looks great; looking forward to having this in dartpad!

**Comment by lukechurch** [comment]
@kasperpeulen has already done this!
