### ISSUE TITLE
Better linking support for navbar buttons

### ISSUE THREAD

**Issue by tusharsadhwani** [dart-lang/dart-pad#1724]
![image](https://user-images.githubusercontent.com/43412083/103914638-25d61800-5130-11eb-98f8-96f3c77113dc.png)

I think it would be better for the Install SDK (and maybe the New Pad button as well) to use `<a>` Anchor tags instead of programmatic redirects using js/dart.

This would provide support for Ctrl+clicking on the buttons to open it in new tab, and middle mouse button support.

Any reasons why it is done programmatically right now? Looking at the code, it should be straightforward to implement this, just looking for a go-ahead/advice before I work on a PR.

**Comment by RedBrogdon** [comment]
The other buttons are more "button-like" in terms of their intended uses, which is why they're implemented with simple event handlers. The Install SDK button is a more recent addition, and inherited the pattern.

I don't have a hard opinion on not using an anchor (and the reason for you suggestion seems valid). I imagine it would involve using a different MDC component (or none at all), though, and I'd be concerned about the following:

* Altering the design in a noticeable way (we'd have to loop in our designer)
* Causing the code to be slightly more difficult to maintain, since one "button" would use a different element.

One alternative would be to check the mouse event to see if the control key is down, and if so open the URL in a new tab. You could also just *always* open it in a new tab, since I imagine most users wouldn't mind.

**Comment by tusharsadhwani** [comment]
The change wouldn't be with the mdc button, it can still remain a button, we could just wrap with with an anchor tag in the html.

It would deviate from the identical markup and buttons using the same exact initialisation code yes, but I think it's worth the added feature.

I'm also fine with the "always open in a new tab" idea, but what about the "New Pad" button? I'd like to be able to open a new pad in a new window, to not lose any current progress.

**Comment by parlough** [comment]
Thanks for the issue and the suggestion!

The DartPad frontend/UI has been rewritten and the navbar is now different as well as the behavior of these buttons, so I'm going to close this issue as obsolete. If you have any feedback about the new buttons, please open a new issue with details in relation to the newest implementation. Thanks again!
