### ISSUE TITLE
After Print(), a new line is getting added. Not able to print texts in horizontally using any form of iterators.

### ISSUE THREAD

**Issue by chidhu07** [dart-lang/dart-pad#1725]
Kindly refer to the for loop and the respective output in the console
![Dartpad issue](https://user-images.githubusercontent.com/43671955/103957976-edefc480-5171-11eb-866e-312066b6ecb9.JPG)

**Comment by parlough** [comment]
Unfortunately this is not a problem with Dartpad, but rather the intended functionality of Dart's print method. In environments where you can access `dart:io` you can use `stdout.print` but on the web that is not available. 

Therefore, to achieve the desired functionality, there's a few different things you can do. If you want to simply print 5 '*' on one line you could use `print('*' * 5)` replacing 5 with any integer or integer variable. Otherwise you could build one string and print that out. This can be done through normal concatenation, using [`.join()`](https://api.dart.dev/stable/2.10.4/dart-core/Iterable/join.html) on a list, or with a [`StringBuffer`](https://api.dart.dev/stable/2.10.4/dart-core/StringBuffer-class.html).

**Comment by domesticmouse** [comment]
Closing this out as WAI. Thanks for the detailed explanation @parlough =)
