### ISSUE TITLE
dart-pad shows error in non-existing line

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dart-pad#1743]
Go to https://master-api.flutter.dev/flutter/material/BottomNavigationBar-class.html.
The dart-pads embedded in that page show an error referencing a line number that not part of the code shown in the dart-pad:

![Screen Shot 2021-01-28 at 10 05 45 AM](https://user-images.githubusercontent.com/1227763/106179882-78fc2300-6150-11eb-9bd9-26faec2f654f.png)

/cc @johnpryan

**Comment by RedBrogdon** [comment]
@miquelbeltran spotted this as well. We believe it's due to the TODO method that was recently put in for his codelab changes. For some reason the warning wasn't popping up before now, nor is it showing up in pure Dart code.

I've asked Miguel to send in a PR adding an ignore to the offending code, since we do want to keep the name.

**Comment by johnpryan** [comment]
Closing since it looks like this is fixed by #1745
