### ISSUE TITLE
DartPad fails to compile when you use Chrome devtools to change time zone.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart-pad#1746]
## What happened?

Used Chrome devtools to change location/time zone to Mumbai.
(Devtools > Other tools > sensors)

Opened dartpad.dev.
Tried to compile program, but got 
```
Error compiling to JavaScript:
XMLHttpRequest error.
```
from compiler and
```
error: XMLHttpRequest error - line 1
```
from analyzer.

Appears using this feature sets a header which is disallowed by CORS.
That makes it much harder to use Chrome to explore problems that only happen in certain time zones.

## Steps to reproduce problem

Open Dartpad.dev. Sample program is fine.
Run program. No issue.

Open dev tools (F12), Other tools (triple dot next to "console" or Triple dot at top > Other tools), Sensors
Select a location override. I choose Berlin, which is same *time zone* as me.
Press "run" in dartpad. Get XMLHttpRequest errors from compiler and analyzer.

Deleting the "Locale" field of the override removes the error, but that's not something a user can be expected to figure out.

### Browser

Browser: 
Chrome

Version:
Version 88.0.4324.104 (Official Build) (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

No, not in this browser. Also reproduces in incognito windows.

> Are there any warnings or errors in your browser's JavaScript console?

There are!

> If so, paste them below:

```
Access to XMLHttpRequest at 'https://v1.api.dartpad.dev/api/dartservices/v2/document' from origin 'https://dartpad.dev' has been blocked by CORS policy: Request header field accept-language is not allowed by Access-Control-Allow-Headers in preflight response.
```

### Machine

Operating system:

Windows 10

Version:

current

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
void main() {
  for (int i = 0; i < 5; i++) {
    print('hello ${i + 1}');
  }
}
```
(Default sample)

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
Error compiling to JavaScript:
XMLHttpRequest error.
```

**Comment by RedBrogdon** [comment]
What a fascinating bug.

I can confirm this behavior on my local machine. From the network traffic, it looks like the OPTIONS request ([relevant MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers)) sent to verify CORS policy receives this info about which headers are valid for inclusion in the real request:

    Origin, X-Requested-With, Content-Type, Accept

When later, due to the timezone override, Chrome wants to use `Accept-Language: mr_IN` in the request, it fails the CORS policy check.

I imagine we can find a way to change the allowed headers returned when OPTIONS requests are made. IIRC we had an issue with CodePen and Firefox at one point that caused us to tweak some things.

@lrhn, is this issue a serious problem for you right now, or just something you noticed while using DartPad? Either way, thanks for reporting it. I'm just trying to gauge priority.

**Comment by lrhn** [comment]
I found the workaround after I started typing the issue, so it's not a big issue for me. Just surprising, and if someone else hits it, it's not obvious that they'll figure out what to do (unless they manage to find this issue).

**Comment by lrhn** [comment]
No longer fails to compile or load, but the loaded code also completely ignores the setting. Filing new bug for that.
