### ISSUE TITLE
Embedded Dart Pad for null-safe Dart cheatsheet does not compile

### ISSUE THREAD

**Issue by theacodes** [dart-lang/dart-pad#1766]
## What happened?

An embedded Dart Pad with null-safety enabled doesn't fails to compile a valid code sample.

## Steps to reproduce problem

Go to [this embedded example](https://dart.dev/codelabs/dart-cheatsheet_migrated#code-example-13) and copy/paste the solution into the code and press run. 

This is the result:

![image](https://user-images.githubusercontent.com/250995/108116240-436c9a80-7069-11eb-8197-86c513522a19.png)

The output error message (`Error compiling to JavaScript: Instance of 'minified:fN'`) is unhelpful, clicking "Show" reveals more details:

![image](https://user-images.githubusercontent.com/250995/108116385-79aa1a00-7069-11eb-8d9f-0bc63393219f.png)

These errors are on the test code, not the user-supplied Dart code.

This same set of code compiles and runs fine on nullsafety.dartpad.dev:

https://nullsafety.dartpad.dev/64c1df94f51514e5f4130077d9fdf62d

### Browser

Browser: Chrome

Version: Version 88.0.4324.150 (Official Build) (x86_64)

### Machine

Operating system: macOS

Version: 10.15.7 (19H512)

**Comment by rakudrama** [comment]
Some random notes:
- `LateInitializationError` was removed. The language specification was changed to not require a specific error for misuse of a `late` variable (https://github.com/dart-lang/sdk/issues/44361#issuecomment-737672074). This is why the diagnostic code no longer compiles.
- I'm not sure that I would use `late` in this context, since an initializer list would work just as well.
