### ISSUE TITLE
code completion is flickering during typing

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart-pad#179]
The completion is flickering while I'm typing.
![](http://i.imgur.com/iaqpJRN.gif)

I saw an other codemirror demo that doesn't flicker in this way, so maybe it is not that difficult to fix this:
![](http://i.imgur.com/u2uo6WA.gif)

**Comment by devoncarew** [comment]
My guess is its because we're sending to the server for completions for each key press. Currently that's about a 200-300ms round trip. That's enough time to cause flickering.

The other codemirror completers are in general filtering through a small list. That's a < 1ms operation. So even though they are also asking for all completions for each keystroke, no flicker.

I think we'll need to recognize when a completion request is substantially similar to the last one, and filter the results from the last one instead of sending to the server again. It's likely this logic can be put in the `DartCompleter`, and doesn't have to complicate the code calling that or the backend.

**Comment by kasperpeulen** [comment]
@devoncarew What you propose seems like a smart solution, and would probably make the completion faster, but I still don't really get why code mirror is actually removing the popup here.

I've been trying to understand the logic of codemirror.js a bit better, and codemirror does understand that it only needs to update the completion in this cases, but it still also removes the popup, just before the request to the server is send, which is a bit unfortunate.

If I comment out the following line in codemirror.js:
```javascript
function activity() {
  clearDebounce();
  var pos = completion.cm.getCursor(),
    line = completion.cm.getLine(pos.line);
  if (pos.line != startPos.line || line.length - pos.ch != startLen - startPos.ch ||
    pos.ch < startPos.ch || completion.cm.somethingSelected() ||
    (pos.ch && closeOn.test(line.charAt(pos.ch - 1)))) {
    completion.close();
  } else {
    debounce = requestAnimationFrame(update);
    //if (completion.widget) completion.widget.close();
  }
}
```

I do get a very fluent experience:
![](http://i.imgur.com/dWWqkrO.gif)

**Comment by devoncarew** [comment]
I'm not familiar enough with that code to know if there'd be side effects. Possibly it's there to fix other issues? I'd file a bug against the codemirror project (https://github.com/codemirror/codemirror) - Marijn is very responsive.

**Comment by kasperpeulen** [comment]
filed an issue at codemirror: https://github.com/codemirror/CodeMirror/issues/3157

**Comment by kasperpeulen** [comment]
this would be fix if we get this commit in: https://github.com/codemirror/CodeMirror/commit/e29fecf2127bae8924d13beb06f37d9fed91d739

**Comment by kasperpeulen** [comment]
this one is fixed now
