### ISSUE TITLE
Small issues with unsupported imports

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#1826]
The dart-service's `getAllImportsFor` function is the code which collects all of the imports found in the DartPad script. The use of Scanner probably results in a very performant function, but currently has a few bugs. Given the following simple script:

```dart
library a;
import 'package:foo';
```

an error is reported: "line 1: Unsupported input: package:foo". Here are the issues though:

1. [ ] It says "line 1". This is because the DartPad front-end is not given any span information, and `getAllImportsFor` returns Strings representing the URI of each import; no other information.
2. [ ] If I introduce a second bad import, only the first is reported.
3. [x] If I introduce an export before the import, the error is not reported:

   ```dart
   library a;
   export 'dart:core';
   import 'package:foo';
   ```

   We might want to introduce a second error similar to "unsupported import" like "exports are unsupported".

4. [x] If I introduce a `part` directive before the import, the error is not reported:

   ```dart
   library a;
   part 'b.dart';
   import 'package:foo';
   ```

   This is not so bad because I don't think there is any possible part that you could specify which would result in otherwise valid code. Similarly `part of` prevents the error from being reported, but also similarly can never be valid code for a DartPad script.

5. [x] The String-scanning bit leads to weird errors with unorthodox Strings. For example `import '' 'dart:async';` is legal (I think sometimes people wrap long imports?) but DartPad does not accept it, and displays "Unsupported input:" (with an empty string).

Obviously most of these issues are just bad UX with bizarre user input, but I think the first two would be good to solve.

**Comment by srawlins** [comment]
To fix the latter issues, you could fully parse the text; this should not perform badly since most requests involve a full parse etc. anyway. Something like:

```dart
var unit = parseString(content: sourceText, path: ..., featureSet: ...).unit;
final directives = unit.directives.whereType<UriBasedDirective>();
```

Or use the existing analysis infra.

**Comment by domesticmouse** [comment]
> To fix the latter issues, you could fully parse the text; this should not perform badly since most requests involve a full parse etc. anyway. Something like:
> 
> ```dart
> var unit = parseString(content: sourceText, path: ..., featureSet: ...).unit;
> final directives = unit.directives.whereType<UriBasedDirective>();
> ```
> 
> Or use the existing analysis infra.

Uhm, this appears to have been shipped as https://github.com/dart-lang/dart-services/pull/695/files#diff-a14f99d4ef1b6791c225138cff084882ac0b7ac614056835ebc71c2f3b3e6874R8

I'm curious @srawlins, what else is outstanding before we can close out this bug?

**Comment by timmaffett** [comment]
@domesticmouse https://github.com/dart-lang/dart-services/pull/695/files#diff-a14f99d4ef1b6791c225138cff084882ac0b7ac614056835ebc71c2f3b3e6874R8 does indeed fix the generation of the unsupported package list to complete, but it does not fix the first issue listed here, the incorrect line number reported.  ('It says "line 1 • Unsupported import(s):  ...')

(detailed analysis below - read or skip.. lol)

While (within dart-services analyze()) we do have the correct offsets for each illegal import we can't use them to generate a proper `AnalysisResults` response because we must bail out of processing the file early (because of the illegal imports). 
We have to do this by throwing a `BadResponse` exception and this is limited to a single string message that gets sent to the client dart-pad and appears as a `ApiRequestError` exception.   This gets handled within `analysis_results_controller.dart` : `performAnalysis()` by manually creating an `AnalysisIssue` object with the error message and assigning it a line number of 1 because no location/offset is known (and indeed it could now be a list of unsupported imports which had multiple locations).

I propose that the best way to handle this situation is to assign it a line number of -1, and then within `_createIssueElement()` we check the line number and only include the line number when it is >=1.   This will eliminate the possibly confusing/erroneous line number within the error message.
I have submitted PR #2274 that does just this.
The error message now just says "Unsupported import(s): ....".
In fact this fix also will prevent any `BadReponse`=> `ApiRequestError` error that is thrown from having a 'line 1...' prefix attached to it when reporting the error to the end user. 

-----
It of course would be possible to change the way this error is handled within dart-services (not throw `BadResponse`, but instead create proper `AnalysisResponse`) - but here is where it gets more complicated.  Only the AnalysisXXX end points return `AnalysisResponse`, and we need to be able to handle the unsupported imports error reporting across all of the end points (dartdoc,complete,assist,format,...).  We currently do this (and throw `BadResponse`) within a call to `_checkPackageReferences()` from within_`perfLogAndRestart()`.   All analysis related end points follow this code path.   I just don't think the benefit would be worth the amount of code that needed to change.. just to be able to report a list of unsupported import line numbers that the user can easily find themselves, as they are at the headers of the files.
