### ISSUE TITLE
The 'dart:io' library cannot be imported in dartpad.dev and "stdin.readLineSync()" cannot be used without it. What's the fix please?

### ISSUE THREAD

**Issue by pro-sports** [dart-lang/dart-pad#1853]
I am trying to use the 'dart:io' library to write  "stdin.readLineSync()" to get console input in dartpad.dev but the problem is that upon running the code I get an error which says "Unsupported import 'dart:io' " and if I don't import this library, then upon running the code again, it says "getter not found: 'stdin.' ". 

I don't know how to fix the problem here. It seems to contradict itself. Please help me with this. How to get an input from the console with the below code:

`import 'dart:io';`
`voidmain(){`
`String food = stdin.readLineSync();`
`print ("Today's food is $food");`
`}`

@dart-packages-copybara

**Comment by domesticmouse** [comment]
I'm guessing you are trying to write console applications inside a web browser. This is hard, because web browsers don't ship with a console environment.

This is why `dart:io` is supported on non web platforms. https://api.dartlang.org/stable/dart-io/dart-io-library.html

**Comment by RedBrogdon** [comment]
(Adding a little extra context, since this looks like @pro-sports' first GitHub issue)

As @domesticmouse mentioned, `dart:io` ([docs here](https://api.dart.dev/stable/2.12.0/dart-io/dart-io-library.html)) isn't supported on web browsers. It's a library designed for input and output for native applications (like `git` or `vim`) rather than applications built to execute inside a web browser.

`stdin`, for example, is the "standard input" for an application. When running something on a command line terminal, `stdin` is coming from the terminal itself, and what you type into it is passed to the application. Browsers, though, don't have a "terminal" like that. The pages they load also can't normally access things like files on your hard drive, low-level hardware, and many of the other things that command line applications can do.

As a result, most of `dart:io` just doesn't apply for apps built in web browsers. which is why it's not supported here.

If you're interested in writing a DartPad code example that can handle input, try using `dart:html` to create a `textarea`, or use Flutter, which has a number of UI components that can be manipulated with Dart code.
