### ISSUE TITLE
Special characters are rendered incorrectly in the editor

### ISSUE THREAD

**Issue by Piinks** [dart-lang/dart-pad#1855]
I included a special character in the code for https://dartpad.dev/workshops.html?webserver=https://dartpad-workshops-io2021.web.app/getting_started_with_slivers but I have removed it because dartpad appears to render it as junk.

Where in the source code I used to have a `°`, it shows up in the dartpad text editor something like `^A° ^`.

**Comment by Piinks** [comment]
FYI @johnpryan 
I don't have assigning permissions 😁

**Comment by johnpryan** [comment]
This only happens when DartPad is deployed to AppEngine.  My guess is there's probably a HTTP  header that needs to be set when we load the `instructions.md` files. We should try configuring  Content-Type header to specify UTF-8. (`'content-type': 'text-plain; charset=utf-8'`)

**Comment by RedBrogdon** [comment]
Sounds like this would be a good thing to test during your Firebase hosting experiment?

**Comment by parlough** [comment]
I'm going to close this issue as stale as the frontend and backend setup for DartPad have changed significantly since 2021, including using Firebase hosting instead of app engine. The workshop functionality has also been dropped. If anyone is still seeing issue similar to this, please open a new issue with reproduction instructions. Thanks so much!
