### ISSUE TITLE
Workshop UI editor is too small

### ISSUE THREAD

**Issue by Piinks** [dart-lang/dart-pad#1858]
Resizing the instructions pane is restricted by any code embedded in the instructions.

This can make the other side, where the work is being done, feel **super cramped**, without any option to get more room in the editor. It would be nice if the workspace took precedence and the instructions pane could be smaller.

**Comment by Piinks** [comment]
FYI @johnpryan

**Comment by johnpryan** [comment]
This is a great point. I think we have a few different options:

1. Hide the bottom-right panel panel until the user runs some code, like the main dartpad.dev editor: <img width="649" alt="Screen Shot 2021-05-05 at 4 35 07 PM" src="https://user-images.githubusercontent.com/1145719/117222250-e65ac800-adbf-11eb-8c6d-7d67b21af249.png">
2. Make the Flutter and Code panels two tabs that take up the full height of the right-hand side of the screen. You would only be able to look at one or the other, but we could make this nicer by switching to the Flutter tab after the user presses run, for example.

I think option 2 might be better because it prevents the user from accidentally making the code or Flutter panels too small.
