### ISSUE TITLE
Gradually go from Dart => HTML => CSS

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#188]
I don't know if I'm typical user, but I very very rarely use HTML and CSS in Dart Pad. The UI isn't "gradual", it assumes I want HTML and CSS.

Allow me to opt-in to HTML and CSS. Start with just Dart code, but make it easy to add HTML, and then make it easy to add CSS.

I assume that not having HTML and CSS will make Dart Pad run a bit quicker for pure Dart pads. That is a nice benefit, but not the primary motivator.

There's a feedback weirdness which can be fixed if we opt-into HTML/CSS (or allow a developer to remove a HTML / CSS file). If I have a pure Dart pad, I still see "Hello, world!" printed on my screen. That's pretty weird. I never even looked at the HTML file, why does it print out?  (I know why, but perhaps new users won't know why :)

Suggestion:

Keep the three tabs (Dart, HTML, CSS) but only default to the Dart tab. Allow a user to activate HTML and CSS from those tabs, or deactivate them. If not activated, gray them out and add a PLUS sign. If activated, they have white text (as they do now) and they have a MINUS sign. The Dart tab always remains.

**Comment by sethladd** [comment]
BTW thanks!

**Comment by lukechurch** [comment]
Around 24% of our users interact with HTML/CSS. This doesn't include those who do so with an HTML enabled sample.

At this rate, it doesn't really justify consuming the top right hand panel of the screen for the non-HTML cases.

I agree with Seth, we could make this functionality opt-in, and gist backed so that if they were using an HTML entry they would get the panels.

Being able to opt in to more tabs sets the tone for being able to add more files later.

In the case where there is no HTML, I'd prefer to not need to switch between documentation and output, but to have them both available top/bottom.

**Comment by sethladd** [comment]
> Around 24% of our users interact with HTML/CSS. This doesn't include those who do so with an HTML enabled sample.

Curious, what does "interact" mean?

**Comment by sethladd** [comment]
> In the case where there is no HTML, I'd prefer to not need to switch between documentation and output, but to have them both available top/bottom.

sgtm

**Comment by sethladd** [comment]
See also https://github.com/dart-lang/dart-pad/issues/123

**Comment by devoncarew** [comment]
I think this is largely addressed?

**Comment by sethladd** [comment]
Love the improvements. Let's close out. Thanks!
