### ISSUE TITLE
Clip enum documentation page 404 not found

### ISSUE THREAD

**Issue by sethdeegan** [dart-lang/dart-pad#1903]
When I click on `Open library docs` for Flutter `Clip enum`, it goes to https://api.dart.dev/stable/2.13.1/dart-ui/dart-ui-library.html which is a 404.
![image](https://user-images.githubusercontent.com/54154494/119281447-6b851000-bbfb-11eb-9aed-9f61e1edde9d.png)

**Comment by domesticmouse** [comment]
@srawlins any ideas on how to chase down the source of this bad return?

**Comment by parlough** [comment]
The issue here is client side where the link is manually calculated: https://github.com/dart-lang/dart-pad/blob/master/lib/documentation.dart#L140

This works fine in most cases, only including links for `dart:` libraries, but `dart:ui` is not included in the Dart SDK dartdoc sources, but rather in Flutter's.

Temporarily, a check could be added to exclude `dart:ui`, but it seems worthwhile to implement the link generation for Flutter libraries as well. Perhaps we could link to solely the Flutter API docs(https://api.flutter.dev/flutter/) if the current pad is a Flutter one, as they also include the SDK docs corresponding to their specific Dart version.

**Comment by srawlins** [comment]
Thanks @parlough !
