### ISSUE TITLE
Question about autocomplete in Dartpad

### ISSUE THREAD

**Issue by gosoccerboy5** [dart-lang/dart-pad#1964]
When I type in an object, then a `.` to indicate accessing some sort of property, or a method call on an object, Dartpad will show autocomplete suggestions.
<img width="209" alt="Screen Shot 2021-07-18 at 8 19 27 PM" src="https://user-images.githubusercontent.com/82768218/126089331-71bffa29-28f3-4375-8db2-4bdd04413501.png">
<img width="269" alt="Screen Shot 2021-07-18 at 8 24 47 PM" src="https://user-images.githubusercontent.com/82768218/126089660-60c639c9-2c66-439e-8c6a-b44760d678d3.png">

Why doesn't it show me suggestions when I start typing an identifier? Is it because the editor dartpad uses can't gather enough contextual information to be able to do that? Would it be too invasive on the programmer to have a suggestion pop up in their face every time they type?

**Comment by RedBrogdon** [comment]
Great question. DartPad uses a server backend for static analysis. That means whenever DartPad needs to do something like check your syntax for typos, find out what autocompletions are possible at the current cursor position, or automatically format your code, it sends a request to the server, which responds with the correct information (a list of issues, a set of possible autocompletions, or newly formatted code, respectively). This is done because it's not really feasible to run the Dart SDKs analyzer on the client, within the browser itself.

The downside to this is that there's latency for each of those requests, and as a result, DartPad couldn't really keep up with someone typing along. By the time it had the list ready, you'd already have typed the next character, potentially invalidating the list.

We *do* support autocompletions for identifiers, though. Just hit `Ctrl + Space` whenever you'd like DartPad to show them (you can see that and other keyboard shortcuts by clicking on the keyboard icon in the lower lefthand corner of the window).

Happy coding!

**Comment by gosoccerboy5** [comment]
Thanks for answering! I didn't know the static analysis was server-side..

> We _do_ support autocompletions for identifiers, though. Just hit `Ctrl + Space` whenever you'd like DartPad to show them (you can see that and other keyboard shortcuts by clicking on the keyboard icon in the lower lefthand corner of the window).

Huh, didn't know about that. Thanks! I should really check out that list of keyboard shortcuts.

> Happy coding!

You too 😁
