### ISSUE TITLE
Turn down pre-null safety option

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart-pad#2042]
We intend to turn down the pre-null safety option. The Null Safe toggle will be removed; all code must be null safe, and we can turn down the pre-null safety back-end(s?).

**Comment by RedBrogdon** [comment]
When the channel switcher is launched, that'd be the moment. I don't anyone in the community will be surprised that we're going forward with null safe as the new normal, but it'll be nice to provide a new feature as we're sunsetting the old one.

**Comment by RedBrogdon** [comment]
Twitter research has commenced: https://twitter.com/redbrogdon/status/1448715119907655685 😄

**Comment by SeasonLeee** [comment]
As currently the aforementioned channel switch feature is rolling out already, I see the toggle/switch to turn off the null safety is gone. 

And this lead to an issue, I am trying to run some codes from some old posts, well, to test whatever they are saying in the post is working as expected, and since the code they wrote is pre-null-safety era, there are a lot of trouble to test it.

I think the very nature of `dartpad.dev`'s existence is to give the audience a fast experiment just like we are trying some JS codes in browser's developer's tool, so it might not so wise to let this toggle gone because there still are a lot of pre-null-safety codes or posts out there...

**Comment by domesticmouse** [comment]
There is significant complexity in the code, and RAM costs, for serving both Null Safety and Null Unsafe traffic, and just before turning off the toggle switch null unsafe was seeing about a twentieth of the traffic of null safe. There is always an engineering trade off in supporting features like this. The complexity in the codebase precludes taking on other features. 

So, while we understand your desire for DartPad to support all possible usecases, as the engineering team supporting this functionality we have to make sometimes uncomfortable design trade offs to keep the complexity of the back end reasonable.
