### ISSUE TITLE
Uncaught Error: Unsupported operation: Result of truncating division is Infinity: 12 ~/ 0

### ISSUE THREAD

**Issue by Anwar-Kabir** [dart-lang/dart-pad#2078]
Uncaught Error: Unsupported operation: Result of truncating division is Infinity: 12 ~/ 0

![Capture](https://user-images.githubusercontent.com/19724239/141610809-b9094f07-8fc5-49b5-83fa-d404b7bc3f02.PNG)

this exception handling try on and try catch code working on VS code but not working on dart pad. why ?

**Comment by parlough** [comment]
Hi @Munna-Rahman. This was a [previously noted issue](https://github.com/dart-lang/sdk/issues/46776) and resulted in `IntegerDivisionByZeroException` being deprecated in Dart 2.15 and slated for removal. If you need to catch this error, it seems `UnsupportedError` currently works on both platforms. Since the method does not document or require throwing that specific error though, perhaps using the generic `Error` would be sufficient.
