### ISSUE TITLE
DartPad it's gonna huge thing, for that I suggest this ultimate suggestions !

### ISSUE THREAD

**Issue by ImadBouirmane** [dart-lang/dart-pad#2088]
Hello Dart & Flutter !
I really love waht are you doing and your huge success, so I'm happy to here with you.
I'm an absolute beginner but I do my to be in the line of this big progress of what can Dart do in the world of digital realtion with Flutter to Ui's interfaces technology innovation.
We have a big porject that I decide to be Dart & Flutter with Firebase and Google Cloud our main tools to make this project run here in Morocco.
For that after your last update about Firebase intergartion on DartPad and hiw much that I prefer this tool to make real production nut just in VSCode or Android Studio.
Based on this that's why I want to make this important suggests:
- Make the DartPad a new IDE for Dart & Flutter With Firebase and also Google Cloud Console (Shell) for people and companies that focusing just in Dart & Flutter Technology. We saw how MS VSCode is running on the Web especially the Google Cloud Shell to make all the stuff just in the web without any local environement, so why not it will interetsing for us.
- Dart & Flutter and Firebase is a full stack development process, and as I explaine in the first suggestion to make DartPad a new IDE based on Web and Hybrid Machines and also to be available for Windows, macOS and Linux (Or maybe as an application Mobile to make fun ). For that we want to bring all tools on DartPad like Packages, Extensions from other technologies integrations and more like that 
- Develop more features on development process just like in VSCode for example and bring the ability to test real apps with Hot Reload, Restart, DevTools, etc ...
If you will do this it's gonna be great !

With all my respects for your efforts !

best Regards

**Comment by srawlins** [comment]
Thanks for the feedback!

DartPad is really intended to just be a playground for Dart and Flutter. dartpad.dev is a great place to share snippets or try out an idea or play with syntax, and the code also supports embedded pads in documentation and articles, and workshops for education.

Beyond that, I think DartPad is not the right starting place for a Web-based IDE for Dart/Flutter/Firebase projects. As you say, the new https://vscode.dev/ product is inspired, and Dart has really great support in most popular IDEs. There is probably a different starting point for writing such a web IDE.

That being said, to your last point:

> Develop more features on development process just like in VSCode for example and bring the ability to test real apps with Hot Reload, Restart, DevTools, etc ...

These ideas are well within the realm of what DartPad aims to do, and I can see us supporting these features with high priority, in order to showcase the power of Dart and Flutter. Search the issue tracker for relevant individual issues and Thumbs Up your favorite asks.

CC @RedBrogdon

**Comment by RedBrogdon** [comment]
Thanks for your suggestions, @ImadBouirmane. Unfortunately I think a number of them are out of scope for the size of the team we have (while I'd love to more online IDEs featuring Flutter and Dart, we definitely aren't staffed to turn DartPad into one). 

Some of your suggestions are likely to come to DartPad eventually, though, such as hot reload.
