### ISSUE TITLE
Turning off null safety for an old gist

### ISSUE THREAD

**Issue by osaxma** [dart-lang/dart-pad#2115]
## What happened?

I'm unable to turn off null-safety for an old DartPad:

https://dartpad.dev/?id=0fbdf1a3e4b0ffc6e1b433f0fd351cf0 

The button for turning `null-safety` off is not there anymore.

I've tried modifying the URL to:
```
https://dartpad.dev/?id=0fbdf1a3e4b0ffc6e1b433f0fd351cf0?&null-safety=off
```
But that does not work. 

I added `// @dart=2.9` at the top of the file which made the errors disappear but then I get the following error in the console:

```
Error compiling to JavaScript:
/tmp/dartpadOXMQLI/lib/bootstrap.dart: Warning: Interpreting this as package URI, 'package:dartpad_sample/bootstrap.dart'.
/tmp/dartpadOXMQLI/lib/main.dart:1:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart=2.9
^^^^^^^^^^^^
```

### Browser

Browser: Chrome

Version: Version 96.0.4664.110 (Official Build) (x86_64)

---- 

The DartPad in question was shared in StackOverflow to show a certain behavior but now it cannot be compiled. I, and many others, have shared many DartPads in the past for StackOverflow Questions & Answers and it's sad to know that all of them will fail to compile. It does not make sense that the viewer has to migrate the DartPad to null-safety just to view a certain behavior. 

I hope, for the very least, that the button is shown based on the publishing date of the gist. I'm not sure what's a good cut-off date but the one I shared above is 11 months old.

**Comment by domesticmouse** [comment]
DartPad no longer supports non null safety. Please update sample as appropriate

**Comment by osaxma** [comment]
@domesticmouse The issue is that it's not only one gist/sample. As mentioned in the footnote, there are many StackOverflow questions/answers of mine and others that were written before null-safety and now they won't compile. At least previously the viewer can use the button to switch null safety off. 

My complaint is that a lot of these questions/answers became useless since they won't compile (and it's not easy for the viewer to migrate a DartPad to null-safety). I honestly don't know how significant is that and the issue only presents one example.

**Comment by RedBrogdon** [comment]
@osaxma, you raise a fair point, and when making the decision about how to handle null safety going forward, we definitely considered the work that devs had put into the existing set of DartPad gists that had been created. That's the reason we originally added null safety as an option, rather than simply switching to it by default at the launch of Flutter 2.

In the time since that launch, though, maintaining the ability to use both null-safe and non-null-safe was making more and more of an impact on our ability to add features and keep DartPad maintained well. For example, we probably would not have been able to launch package support last year if we'd continued to support non-null-safe code. We would have needed to offer different versions of packages based on whether null-safety was in use, and deal with the fact that newer packages might not even *have* non-null safe versions, and keep Firebase from going crazy.

For this reason, after ten months we said goodbye to the null safety switch. I can assure you, though, that it wasn't done lightly, nor without considering the needs of our long-term users.

**Comment by PeperMarkreel** [comment]
I am saddened as well that I can't switch to disable null safety. Indeed, a lot of examples are not updated to null safety and it isn't trivial to update the example (for me at least). I understand you have to make choices in where to spend development time, but is it possible to publish the old version of dartpad somewhere where the disable null safety switch still exists? Under a "not maintained" declaration? So no more development time is consumed by it, but that the functionality of the old version is still available? The non null safe branch doesn't have to be maintained because new examples will be null safe (or be published in a non null safe dartpad)

I am afraid that a lot of examples will never be updated and will shower newcomers with error messages and will make the learning curve much more steep and more confusing.
