### ISSUE TITLE
saving works

### ISSUE THREAD

**Issue by ultraamateur** [dart-lang/dart-pad#2169]
Hi, is there a way that i can save my works on dartpad (that i couldnt recognize ) ? Otherwise it would be nice to be able to save my works with a name for checking in the future. (i dont mean to share with someone on git, just saving small code snippets with meaningful names to see them later)

**Comment by RedBrogdon** [comment]
DartPad doesn't offer any sort of storage option built into the site. We've done this by design to keep the architecture, security, and privacy concerns manageable.

You can use GitHub to create a Gist, though, which DartPad knows how to load: [https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide](https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide).

We're also tracking a feature request to add GitHub authentication to DartPad (#1095), which would allow for gist creation within the site's UI. So far, however, we haven't had engineering bandwidth to dedicate to it.
