### ISSUE TITLE
Bold text is difficult to distinguish

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dart-pad#2218]

**Comment by timmaffett** [comment]
I played with styles a bit and it seems that there are several (obvious) options:
  a) include a heavier weight version of the Roboto font - current bold is 600 or 700. I think this would be less legible.
  b) change to the Roboto Mono for bold so that spacing is wider
  c) adding additional slight color change, I found #cef (from #fff) gives a subtle shift to blue that
  d) both b) and c)

I have included examples below (the bold text is 'these widgets')

Existing:
![existing](https://user-images.githubusercontent.com/3639881/162221407-73b3e22a-5310-4ecb-8b85-5239443eac86.png)

Roboto Mono Only:
![mono_only](https://user-images.githubusercontent.com/3639881/162221484-bce64885-7cfb-4a38-9f27-986db86fcb3d.png)

Color Only:
![color_only](https://user-images.githubusercontent.com/3639881/162221544-0c4b0253-2595-4214-839e-eae26773c018.png)

Roboto Mono and Color:
![mono_and_color](https://user-images.githubusercontent.com/3639881/162221590-8353af63-9f1a-4af3-9840-1140a53bef17.png)

Of course there are endless other options, I thought I would share my experiments.

**Comment by parlough** [comment]
With https://github.com/dart-lang/dart-pad/issues/2808, support for workshops was dropped, so I'll close this as obsolete. If anyone reading this desires a feature similar to this in DartPad or a new form of workshops, please discuss that in a new issue. Thanks!
