### ISSUE TITLE
Codelabs / Editors showing issues

### ISSUE THREAD

**Issue by selhuberb** [dart-lang/dart-pad#2231]
Hi Team,

I started having a look into Flutter development and I'm therefore having a look into your provided trainings.
At the following training nearly every Dart editor is showing issues:
https://docs.flutter.dev/codelabs/layout-basics

I'm using Chrome Version 100.0.4896.75 (Official Build) (x86_64) on macOS Monterey 12.3.1.
Maybe you want to have a look into it.

<img width="798" alt="dart-editor-issues" src="https://user-images.githubusercontent.com/38206585/162616284-71a81b4c-238c-4abb-94ae-abbeb14eb7fc.png">

Cheers

**Comment by domesticmouse** [comment]
I've opened an issue on flutter/website's issue tracker as the issue is that the samples need to be update for the new lint rules. Thanks for the report!

**Comment by domesticmouse** [comment]
Actually, there is something more interesting going on here. As alluded to in the image above, the warnings are for lines not actually in the sample code. I'm guessing it is in the test code?

**Comment by johnpryan** [comment]
I agree this is probably an issue with the test code. It's hard to debug because the test code is appended to the `main.dart` script, so the line numbers seem to be incorrect.

**Comment by timmaffett** [comment]
I took a look at this last night and I noticed that the warnings were always like 8,12 and 36 lines past the end of the example source.  When I took a look at the test code I noticed that there were `Color()` constructors calls on lines 7 and 11 and then an `if (rows.length == 0) {` on line 35.. which directly correspond to the warnings, so you are right, this is definitely the warnings from the test code that is being appended to the example source.

**Comment by timmaffett** [comment]
While exploring the Flutter area within the Google IO Adventure I happened upon the 'win a dash' area where you must fix 3 dart/flutter examples.  Unfortunately this same bug reared it's head there as well, and two of the examples had 'warnings' past end end (within the test code).   I suspect that this area was used last year... but since then the analyzer now finds these warnings and displays them.  It is easy to imagine how something like this slips through the cracks.. but not an idea look.. 

This motivated me to fix this bug once and so this can be avoided in the future.  I have submitted PR #2276 . Example and details below:

(Example from top of thread which shows the problem: [problem shown here](https://docs.flutter.dev/codelabs/layout-basics) )

Same "layout-basics" example with new PR applied:  [problem fixed here](https://timmaffett.github.io/test_infos/inject_test_with_warning.html)

If you show the test and edit the dart code to trigger an analysis you will see the warnings appear for the test code. Adding warning/error to dart code you can see how you can click among the issues and the appropriate tab is activated/source shown.

--------------------------------------------------
Details:
1) If there are info or warnings within the test code they are omitted from the list of issues unless the test is showing.
Errors are never omitted.
2) When the test is showing then these info/warnings are displayed (for example so the problems can be found and fixed, or if the user edits the test and more info/errors appear).
3) All info/warning/error issues within the test code always have the correct line numbers, and appear as 'Line X of test.dart'
 
If you click on issues from test or user dart code the appropriate tab is activated and the cursor is placed at the correct location within the source code.

The net effect of this is that for things like the google io issue, or the issue that prompted this original issue, the messages will not be there from the start to confuse the user, if the user does have the test showing then analysis issues that do occur within the test will be displayed, but with the correct line number and 'filename'. 

Example from google io adventure, I think there was  like 43 lines in the the dart tab's code in the example pictures below.

![GoogleIOFlutter_DashPushDartPad_TestWarnings](https://user-images.githubusercontent.com/3639881/168203898-a117c65a-f62f-4b69-a68d-61c14bfef0f5.png)
