### ISSUE TITLE
@immutable eroor

### ISSUE THREAD

**Issue by Mryuksel101** [dart-lang/dart-pad#2296]
I have some mistakes when I want to use @immutable

![Ekran Görüntüsü (422)](https://user-images.githubusercontent.com/99680265/173145994-100953a1-0f99-446d-bf41-9424bbad9e9b.png)

**Comment by domesticmouse** [comment]
First up, please read https://codewithandrea.com/articles/beginners-guide-coding-questions/

Secondly, yup there are coding errors. If you click the blue "show" button next to the "1 issue" label in the bottom status bar I suspect you will get a hint as to what the issue is. I believe adding a constructor to your `Student` class will help...
