### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by deppimaracanau** [dart-lang/dart-pad#2331]
try to user...and...

Unsupported import(s): (package:open_file/open_file.dart, package:path_provider/path_provider.dart, dart:io, package:dio/dio.dart)

**Comment by parlough** [comment]
Hi @deppimaracanau, thanks for opening an issue. 

Since DartPad runs on the [web platform](https://dart.dev/overview#web-platform), `dart:io` and packages, such as `package:path_provider`, which depend on it are not supported. DartPad also has a specific set of packages that are supported, which doesn't currently include the packages you are trying to use. To see a list of supported packages, you can click the "i" (information) icon in the bottom right corner of DartPad.

If you'd like to see other packages supported, you can [open a new issue](https://github.com/dart-lang/dart-pad/issues/new/choose) with why you'd like to see a specific package supported.

Thanks again and let us know if you need any further help!

**Comment by zzzh** [comment]
> Hi @deppimaracanau, thanks for opening an issue.
> 
> Since DartPad runs on the [web platform](https://dart.dev/overview#web-platform), `dart:io` and packages, such as `package:path_provider`, which depend on it are not supported. DartPad also has a specific set of packages that are supported, which doesn't currently include the packages you are trying to use. To see a list of supported packages, you can click the "i" (information) icon in the bottom right corner of DartPad.
> 
> If you'd like to see other packages supported, you can [open a new issue](https://github.com/dart-lang/dart-pad/issues/new/choose) with why you'd like to see a specific package supported.
> 
> Thanks again and let us know if you need any further help!

DartPad is useless if it can't import packages people want to try on it.
