### ISSUE TITLE
Add master channel

### ISSUE THREAD

**Issue by awh6al** [dart-lang/dart-pad#2342]
it's very painful to switch from channel to another in flutter in local environment and it became a wast of time even in small regression tests, so it's helpful feature to be added.

**Comment by domesticmouse** [comment]
Due to the various architectural trade offs in building a service like DartPad, it isn't possible to track master, which changes multiple times a day. 

Hey @gspencergoog, if I recall correctly, you built out some tooling to cache dart and flutter versions to make Flutter branch switching cheaper and quicker. Any chance of making that tech more broadly available?

**Comment by gspencergoog** [comment]
I did, but it was pretty rudimentary.  Basically some bash functions that would swap out a symbolic link to a branch-specific cache directory when the checked out branch matched one.

I think the better (and actually maintained) version of this is [Flutter Version Manager](https://fvm.app/docs/getting_started/overview), a third party package for managing Flutter versions.
