### ISSUE TITLE
Feedback on "install SDK popup" experiment

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart-pad#2407]
I just got hit by this experiment on dartpad.dev. 

<img src="https://lh3.googleusercontent.com/pw/AL9nZEX4Y0sdezJEfwSQ5ltJrXZexvWlRS3zB4HpEX1C8wP5BAqCFyFrFSp1nPjpT6nyBPRyHZcpj6ID8S-o1WVPYzLmL846PlAOYAm41-XopnUnWDFYCGQ_nCbfxkU7EmNjGez9Un0-zwiYB87X4FxfTmE=w765-h447-no?authuser=0">

(Found https://github.com/dart-lang/dart-pad/pull/2397 relating to the experiment, which is why I think it's an experiment.)

Here's my feedback.

I *HATE* it. Viscerally. Enough to spend 20 minutes figuring out how to make a screenshot so I could lodge a complaint.

Modal dialogs are user unfriendly. They get in the way of what the user is _actually_ trying to do. Unless that is the goal, and it should only be a goal in order to either protect the user from danger, or to request essential input from the user that they cannot progress without, modal dialogs should be avoided.

Providing awareness of being able to download Flutter is fine, but a flyout or a top-bar can do that without taking over the entire screen.
From someone who actually uses Dartpad often, because it's *more* convenient than starting a local editor, please reconsider this design! Don't interrupt me while I'm having a good time.

**Comment by domesticmouse** [comment]
FYI @johnpryan

**Comment by johnpryan** [comment]
Thanks for the feedback, cc'ing @maguinis. Instead, we could highlight the "Install SDK" button, instead of displaying a modal dialog. Maybe we could draw attention to the "Install SDK" button by using an absolutely-positioned callout like this:

<img width="344" alt="Screen Shot 2022-11-07 at 10 30 08 AM" src="https://user-images.githubusercontent.com/1145719/200387253-953fc963-0c41-4688-8231-c4733ed68ffe.png">

**Comment by craiglabenz** [comment]
fwiw, I completely agree with @lrhn on the desire to revert this.

**Comment by johnpryan** [comment]
This experiment is no longer running. We'll need to get the UX right if we decide to do this permanently.
