### ISSUE TITLE
avoid_init_to_null issue doesn't show when declared const

### ISSUE THREAD

**Issue by Acid-Free** [dart-lang/dart-pad#2417]
## What happened?

When assigning null to a newly declared variable, avoid_init_to_null issue shows up in the bottom-right of the screen.
![image](https://user-images.githubusercontent.com/49774633/204438013-93530e02-0c08-4bd9-98cc-2b6bb2b0b96a.png)
However, when declared as const, the issue disappears.

## Steps to reproduce problem

1. Define a constant variable [with const]

### Browser

Browser: firefox

Version: 107.0 (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
[paste warnings or errors here]
```

### Machine

Operating system: Windows 10 Home Single Language

Version: 19044.2251

### Code

```
main() {
  const int? a = null;
  print(a);
}
```

**Comment by parlough** [comment]
Thanks for filing an issue!

This is expected because `const` declarations must be initialized in the declaration and cannot change, so if you want it to be `null`, you need to explicitly do so. 

Note the lint also won't appear if the declaration is `final` as `final` variables cannot be read/accessed until assigned, so if you want it to be `null` and use that variable, you need to explicitly do so.

```dart
void main() {
  final int? a = null;
  print(a);
}
```

The lint is intended for variable declarations (using `var` or just a simple type declaration such as `int?`) with a nullable type as they automatically get initialized to `null`.
