### ISSUE TITLE
Simple double addition bug

### ISSUE THREAD

**Issue by theShreyans** [dart-lang/dart-pad#2455]
## What happened?
Between 4.1 and 7.1 any number with .1 as base, added with 0.1 results in infinity (i.e: 5.1 + 0.1 = 5.1999999999).
The intended result should be double (i.e: 5.1 + 0.1 = 5.2).

## Steps to reproduce problem
1. Create double variable 
2. Try to do simple addition using any number before the decimal starting from 4 and keeping the number after the decimal at 1 ( 4.1, 5.1, 6.1, 7.1).
3. Now add 0.1 (i.e: 5.1 + 0.1)

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

```
void main() {

   final mappedNumber0 = (5.0 + 0.1);          // 5.1
   final mappedNumber1 = (5.1 + 0.1);          // 5.19999999999
   final mappedNumber2 = (5.2 + 0.1);          // 5.3

   print('$mappedNumber0 | $mappedNumber1 | $mappedNumber2');
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
5.1 | 5.199999999999999 | 5.3
```

**Comment by parlough** [comment]
This is expected for doubles due to how floating point values work in any language (including Dart and JavaScript) which use [IEEE-754](https://en.wikipedia.org/wiki/IEEE_754) 64-bit floating point numbers.

You can read more by reading this comment specific to Dart (https://github.com/dart-lang/sdk/issues/47081#issuecomment-911387804) or this guide about [What Every Programmer Should Know About Floating-Point Arithmetic](https://floating-point-gui.de).

To learn more about numbers in Dart and Dart on the web, see [Numbers in Dart](https://dart.dev/guides/language/numbers).

Thanks for opening an issue and let us know if you have any more questions :D
