### ISSUE TITLE
Delay in dartpad

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/dart-pad#2489]
## What happened?

Randomly, at least I couldn't find any pattern, `Future.delayed` takes more time than it should to complete. If I rerun this, they will differ again,

![image](https://user-images.githubusercontent.com/52160996/233450863-3f6bf14c-69e5-41a7-8195-c4b16a4331c0.png)

### Browser

Browser: Google Chrome

Version: 112.0.5615.137

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)? Only [Kaspersky Protection](https://chrome.google.com/webstore/detail/kaspersky-protection/ahkjpbeeocnddjkakilopmfdlnjdpcdm)

### Machine

Operating system: Windows 11 Pro

Version: 22H2

### Your code

```
import 'dart:async';
import 'dart:collection';

String hour(DateTime date) {
  return '${'${date.hour}'.padLeft(2, '0')}:${'${date.minute}'.padLeft(2, '0')}:${'${date.second}'.padLeft(2, '0')}';
}

void main() async {
  final processor = MyProcessor();

  print('Start');
  // First function call
  processor.process(() async {
    print('\nStarting first call');
    print(hour(DateTime.now()));
    await Future.delayed(Duration(seconds: 2));
    print(hour(DateTime.now()));
    print('First call completed');
    return 'Result from first call';
  });

  // Second function call
  processor.process(() async {
    print('\nStarting second call');
    print(hour(DateTime.now()));
    await Future.delayed(Duration(seconds: 1));
    print(hour(DateTime.now()));
    print('Second call completed');
    return 'Result from second call';
  });

  // Third function call
  processor.process(() async {
    print('\nStarting third call');
    print(hour(DateTime.now()));
    await Future.delayed(Duration(seconds: 3));
    print(hour(DateTime.now()));
    print('Third call completed');
    return 'Result from third call';
  });
}

class MyProcessor {
  bool _isProcessing = false;
  final Queue<Completer> _completerQueue = Queue();

  Future<void> process(FutureOr<dynamic> Function() func) async {
    final completer = Completer();
    _completerQueue.add(completer);

    while (_completerQueue.first != completer) {
      await _completerQueue.first.future;
    }

    _isProcessing = true;
    final result = await func();
    _isProcessing = false;

    if (_completerQueue.isNotEmpty) {
      final nextCompleter = _completerQueue.removeFirst();
      nextCompleter.complete();
    }

    return result;
  }
  
  bool get isProcessing => _isProcessing;
}
```

### DartPad's output

Did DartPad print anything to the console pane? If so, paste it below:

```
Start

Starting first call
15:03:00
15:03:03
First call completed

Starting second call
15:03:03
15:03:04
Second call completed

Starting third call
15:03:04
15:03:08
Third call completed
```

### Windows output:

```
Start

Starting first call
15:22:45
15:22:47
First call completed

Starting second call
15:22:47
15:22:48
Second call completed

Starting third call
15:22:48
15:22:51
Third call completed
```

**Comment by lrhn** [comment]
Any timer can (seem to) take longer than you ask for. If the Dart runtime is doing something at the time where the timer runs out, the timer event won't be handled until control returns to the event loop.

The DartPad version of this code does seem to have a fairly consistent extra ~1-second delay compared to running the JS code directly on the command line.

**Comment by FMorschel** [comment]
Thank you for the explanation! Should this be left as is? I would think it was better if we at least documented this somewhere easily accessible. If you disagree with me, please feel free to close this issue.

**Comment by lrhn** [comment]
I think I'll leave that to the dartpad developers to decide.

There *is* a delay compared to running the same code on the command line using `node`. If that has a good explanation, it's probably fine. If it's not supposed to be that way, it might be revealing an underlying problem.

I'll leave that to the experts to decide.

**Comment by domesticmouse** [comment]
@lrhn Any idea which experts I should chat with? I doubt this is a DartPad specific issue, more likely a Dart2JS issue.

Any ideas @kevmoo?

**Comment by lrhn** [comment]
Might be a Chrome-specific issue.
I'm seeing the same ca. 1 second slowness on all branches from "old" to "master", but none when running in Firefox (Focus, on my phone, will check in more detail when I get to a desktop).

If so, it might be dart2js itself which is slower on Chrome, which wouldn't necessarily show up when I tested the code on the command line with Node or V8 directly. Those use the preamble JS files instead of the real browser features, and if the overhead it's in accessing those browser features, it only happens in the actual browser.

It's still a very visible difference, and something I'd hope some with benchmark should have noticed og it was a general issue.

I'll try investigating a little more, maybe using browser dev-tools. No promises that I'm competent to find the real cause.

**Comment by lrhn** [comment]
Something seems to be seriously slow with timers in DartPad on Chrome.

I changed the example to use `StopWatch` *and* a timer to count progress along the way:
https://dartpad.dev/?id=7ac1c2637ac1caca2a261693bfdf0df0

The 100 ms timer only fires once per second. If all timers only get to fire once per second, that explains how a delayed future completes almost one second after its duration runs out - that's when the next timer slot is, since it was scheduled slightly after a previous timer slot.

Firefox does not show that behavior.

But WHY is that? (I'll try closing some Chrome windows and see if it makes a difference. Including this one.)

**Comment by FMorschel** [comment]
I'm still testing (missing Ubuntu and Mac to see if this behaviour changes anywhere) but on Windows at least it seems that some Chromium-based browsers have this problem. I've tested on:
- Chromium-based (with this delay):
  - Google Chrome
  - Microsoft Edge
- Chromium-based (no delay):
  - [Opera](https://www.opera.com/download)
- Firefox

**Comment by lrhn** [comment]
One possibility is that DartPad compiled code is throttled because the user code is running in a cross-origin non-isolated frame.

That is apparently a thing in Chrome, but one tick per second seems excessive.

**Comment by domesticmouse** [comment]
As this looks like a specific security concern in the construction of sandbox iframes, I'm going to close this as WAI. Sure it isn't ideal, but DartPad has been engineered for an aggressively antagonistic threat environment known as the web. 

This is why we can't have nice things.

**Comment by lrhn** [comment]
Could it be possible to isolate the sandbox *better*. The idea I got from searching for this issue was that the restriction was greater for _non_-isolated cross-origin code.

I guess isolating too much would make it harder to see and interact with the results, but if the compiled code frame could somehow be completely isolated from the surrounding editor, etc., and only be able to write to its own output DOM element, with all the contents sent from the same server, ... maybe the timers could get less cripppled?

(Hoping, because I do use DartPad for testing, and if timing is completely out of wack, it's much less useful.)

**Comment by domesticmouse** [comment]
The issue with constraining the iframe further is that it will further break our Firebase integration.

**Comment by FMorschel** [comment]
Hey, just an update. Only posting here JIC anyone finds this issue, they know it has been solved.

I'm not sure what happened, but I just tested [the example](https://dartpad.dev/?id=b751c5bb8928dbf3e6755fbdf5221fa0) on Chrome and everything worked just fine.

Tested on two Windows devices and one Android. All working as they should!
