### ISSUE TITLE
The requested URL not found

### ISSUE THREAD

**Issue by natrok** [dart-lang/dart-pad#2587]
https://esflutter.dev/docs/codelabs/layout-basics

No es posible usar la pagina de debugm probado en Opera y chrome

mensaje:
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again

**Comment by parlough** [comment]
Thanks for opening an issue!

It looks like the `esflutter.dev` website is out of date (https://github.com/flutter-es/website), having not been updated since November 2021. So that codelab uses a version of DartPad embeds that no longer exists. You can try to open an issue on their repository or visit the supported English version of the codelab at https://docs.flutter.dev/codelabs/layout-basics. 

There are also multiple great Flutter codelabs on the Google Codelabs website that support Spanish if you want to try them instead: https://codelabs.developers.google.com/?product=flutter
