### ISSUE TITLE
Won't copy unicode combiners

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/dart-pad#2637]
## What happened?

Paste in '🏳️‍🌈'
highlight and copy just that flag
Paste again.
Receive 🏳️‍

Expected: 🏳️‍🌈

Noted: if you hit the right arrow again, the selector doesn't move and you can copy the flag.

**Comment by jtmcdole** [comment]
```
===[🏳️‍🌈]===
  length:    6
  codeunits: 6
  runes:     4
  utf16:     0xd83c 0xdff3 0xfe0f 0x200d 0xd83c 0xdf08
  utf8len:    14
  utf8 bytes: 0xf0 0x9f 0x8f 0xb3 0xef 0xb8 0x8f 0xe2 0x80 0x8d 0xf0 0x9f 0x8c 0x88
===[🏳️‍]===
  length:    4
  codeunits: 4
  runes:     3
  utf16:     0xd83c 0xdff3 0xfe0f 0x200d
  utf8len:    10
  utf8 bytes: 0xf0 0x9f 0x8f 0xb3 0xef 0xb8 0x8f 0xe2 0x80 0x8d
  ```

**Comment by parlough** [comment]
Thanks for the report! I'm surprised anyone noticed this :P 

The underlying issue here is in CodeMirror, likely the same as https://github.com/codemirror/codemirror5/issues/6585.

As the CodeMirror maintainer highlights in that issue, it's unlikely CodeMirror 5 (the version we are using) will see a fix. So I'm going to close this in favor of https://github.com/dart-lang/dart-pad/issues/2743 which discusses exploring a different underlying text/code editor.
