### ISSUE TITLE
Preview version very slow on Firefox

### ISSUE THREAD

**Issue by filiph** [dart-lang/dart-pad#2767]
## What happened?

Trying https://preview.dartpad.dev/ in Firefox 120.0.1 (64-bit) on macOS Ventura 13.6.1 (on a MacBook Pro M1), the app is very slow.

A screencast (sound on, please, I talk through the issue):

https://github.com/dart-lang/dart-pad/assets/919717/f338b32e-e009-4c6b-99ab-90e02a44034b

I tried to do some basic profiling:

<img width="1436" alt="Screenshot 2023-12-21 at 08 01 18" src="https://github.com/dart-lang/dart-pad/assets/919717/54dd18e8-0741-4163-a04b-7fdc1f061aa8">

I'm not familiar with the browser's profiling tool, but I think that what I'm seeing is that Flutter (Canvas?) internally spends a _lot_ of time in `Window.createImageBitmap`.

### Browser

Browser: Firefox

Version: 120.0.1 (64-bit)

Are you using any extensions/plugins that affect website behavior
(particularly those that affect iframes, such as ad blockers)?

- Yes, I'm using uBlock Origin.

Are there any warnings or errors in your browser's JavaScript console?
If so, paste them below:

```
Installing/Activating first service worker. [flutter.js:3:534](https://preview.dartpad.dev/flutter.js)
Activated new service worker. [flutter.js:3:1113](https://preview.dartpad.dev/flutter.js)
Injecting <script> tag. Using callback. [flutter.js:3:1820](https://preview.dartpad.dev/flutter.js)
unreachable code after return statement
[main.dart.js:9804:1](https://preview.dartpad.dev/main.dart.js)
unreachable code after return statement
[main.dart.js:72464:1](https://preview.dartpad.dev/main.dart.js)
Flutter Web Bootstrap: Programmatic. [main.dart.js:8715:22](https://preview.dartpad.dev/main.dart.js)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [canvaskit.js:14:383](https://www.gstatic.com/flutter-canvaskit/726a137e3f99f1fa1788d0586c54009bc32bab1f/canvaskit.js)
WebGL warning: getParameter: The READ_BUFFER attachment is multisampled. 2
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://preview.dartpad.dev/flutter.js
Source Map URL: flutter.js.map
```

### Machine

Operating system: macOS

Version: Ventura 13.6.1

### Your code

What code was in the editor, if any, when the failure occurred? You
can paste it in below:

- The default sample - didn't even need to run it.

**Comment by filiph** [comment]
FWIW, I just tried _without_ using any ad blockers, and the issue persists.

**Comment by devoncarew** [comment]
Thanks for the report! A few things jump to mind:

- we have not looked into perf at all for the flutter web version of the UI; we could easily be doing more rebuilding than is necessary
- we use web plugins to add codemirror to the left side of the UI, and to add an iframe to the right side of the UI. we then stack flutter widgets on top of the plugins (via `Stack`, in order to do things like have the run button float over the text). Perhaps this setup is causing the framework to go down a more expensive `Window.createImageBitmap` route?

**Comment by parlough** [comment]
Without understanding much about Flutter Web its usages of CanvasKit, I think we're experiencing a few issues here. They all seem to be due to our use of platform views (two of them) and the amount of layering introduced.

1. It seems we're hitting Firefox's limit of webgl contexts or similar, so some things just don't work?
2. Even if we reduce that enough, `Window.createImageBitmap` seems to be a lot less performant on Firefox.
3.

**Comment by parlough** [comment]
The core issue here with `Window.createImageBitmap` has been mitigated by https://github.com/flutter/engine/pull/49572 returning to an older mechanism for Firefox. My understanding is that this mechanism still has a few limitations so I'll monitor behavior in Firefox and follow the underlying Firefox performance bug.

The preview UI should now be built with a Flutter build that contains the fix. We can address other performance improvements more specifically.
