### ISSUE TITLE
Should we only use recommended lints?

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-pad#2815]
From discussion in the triage of `package:lints`:

Since DartPad is meant for trying out code quickly and lints do appear as a type of warning, it can be distracting to an initial exploration process to trigger stylistic or performance lints. This is particularly the case for some of those in `package:flutter_lints` around `const` and similar.

Should we instead use the recommended set for all projects?

We could also use core, but I think there's a lot of good teachable moments added by the recommended lints.

**Comment by lrhn** [comment]
I'd personally go for core lints, because someone doing exploratory coding or writing a quick test don't need to be told to add `@override`. It's a reasonable software engineering practice, but it's just not important at the scale of a DartPad snippet.

(And I'm saying that as someone who routinely writes 100+ line things in DartPad, just because it's so accessible that I don't bother starting up an editor.)

Too many warnings can be discouraging for a new user, starting with `core` should show them only the most likely errors, without getting in the way of exploration.

That said, there are a lot of lints in `recommended` that are educational. Of the form "What you're doing is OK, but hey, this would be even better!".
Maybe just exposing `recommended` lints as *hints* instead of *warnings* would be more encouraging to a new user.
Warnings are bad. They say "You're doing something wrong. Stop it!". People can feel chastised and feel like they're not welcome.
Hints are more like "Hey, did you know ...?"

There are *some* lints in `recommended` that only really make sense in large-scale development. They bring very little value in a small self-contained, likely exploratory, code snippet. We could consider entirely omitting those.
Looking at the actual lints in recommended, that would, IMO, be:
    - annotate_overrides
    - avoid_renaming_method_parameters
    - avoid_single_cascade_in_expression_statements
    - empty_constructor_bodies
    - prefer_final_fields
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals

These are mainly things that can easily happen *while* editing. Something you'd want to fix before committing the code to a larger project, but if you are *exploring*, warning about it is really just getting in your way.
An experience programmer can easily say "sure, I'll get to that" or "it'll go away in a moment when I add this other thing". A fledgling Dart programmer doesn't have that experience, and may think this is actually *important*. Putting it before them is a distraction with little benefit.
(I'm on the fence on `unnecessary_late`, but think the educational part is more important.)

We can optimize for different users, and if completely new-to-Dart programmers are the target audience, this is what I'd do: Core lints as warnings, most other recommended lints as hints, except the list above which I'd just drop.

But not all programmers are the same. We probably should let the user configure their lint-level, with the above as the default.
Then someone who likes it bare can do `core` or none, and someone who is going to copy the code into their project, or just like to be told about everything, can use `recommended` or `flutter`.

Remember the choice in a cookie, so you don't have to choose each time.
Maybe give analyzer warning displays an option of inserting `// ignore` or `// ignore-for-file` for the warning.
(Am I just asking for DartPad to be more like VSCode?)

**Comment by natebosch** [comment]
+1 for using core because the recommended set is less useful for dart-pad sized stuff.
