### ISSUE TITLE
Dartpad Behavior Change : Gist File Name Restriction (can load gist only if the file is named "main.dart")

### ISSUE THREAD

**Issue by rxlabz** [dart-lang/dart-pad#2873]
## What happened?

Previously Dartpad was able to open code from a gist.github.com id whatever the gist file name was, but now the gist code is only loaded in darted if the file name is `main.dart`

## Steps to reproduce problem

Open this link : http://dartpad.dev/?id=9d1dbcaf0632e7a4e2ecf0c3fe1f49c1
It fails while the [gist](https://gist.github.com/rxlabz/9d1dbcaf0632e7a4e2ecf0c3fe1f49c1) is a valid flutter file
It still works in the old darted : https://old-dartpad-3ce3f.web.app/?id=9d1dbcaf0632e7a4e2ecf0c3fe1f49c1

Open this link : http://dartpad.dev/?id=945245d37a3f1baf66961f4ba0584be5
this [gist](https://gist.github.com/rxlabz/945245d37a3f1baf66961f4ba0584be5) is just a copy of the previous, only the filename is `main.dart`, but Dartpad can now open it.

**Comment by rxlabz** [comment]
It seems to be the sketch_pad expected behavior, is there a technical reason to load only the "main.dart" file ?

**Comment by parlough** [comment]
It was never intentional for the previous UI to support filenames besides `main.dart`, and to maintain simplicity, the new UI does not currently handle other names.

Is there any reason you need to have a differently named file for a DartPad gist or think it's worthwhile to continue supporting? Thanks for any insight :)

**Comment by osaxma** [comment]
There are many links to dartpad on the internet (e.g. StackOverflow answers, blogs, etc) that are not working anymore because of this change.

I think it's simpler to keep supporting any name than asking the entire community to update their gists.

**Comment by rxlabz** [comment]
@parlough, thank you for your insights. From an external perspective, it's always difficult to understand why replacing a working solution with a less capable alternative, but let's see how it evolves in the future 🚀. In my case, I mostly generate gists from my IDE during training sessions to share examples with participants. Since the IDE's UI allows me to name the created file, it shouldn't be a "blocking change".

**Comment by osaxma** [comment]
The issue is that most of the people who would run into these non-functioning gists are not the authors themselves, but anyone looking at SO answer, reading a blog or a tutorial. 

I personally think DartPad should flexible and graceful towards this -- at least for gists with a single file. But I also don't understand why it is technically complex to accommodate for this. 

I assume any solution that informs the visitor that they need to manually copy the content to a DartPad because there is no `main.dart` would work.

**Comment by devoncarew** [comment]
Thanks for the feedback here! We did add back support for the older format in https://github.com/dart-lang/dart-pad/pull/2880; that should be deployed to the live dartpad in ~10 mins.

It does nag when it encounters the older format.
