### ISSUE TITLE
Removing support for `channel=master` broke Flutter's API docs

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dart-pad#2879]
In Flutter's API docs we are passing `channel=master` as a query param to dart pad to run sample code on the `master`/`main` branch. This broke recently when `channel=master` instead gave us the `stable` channel. Instead of `master`, `main` needs to be passed in now. We are fixing this in https://github.com/flutter/flutter/pull/144329.

This breakage went undetected for some time. I am wondering if there is something we can do to avoid breaking Flutter's API docs on these kind of dart pad changes. This issue is meant as a starting point for that discussion.

**Comment by lrhn** [comment]
If there are external uses of the URI-based API, then it should probably be considered an API, with versioning and breaking change policies.

Seeing it that way would likely have made the transition more explicit and visible:
* A public "breaking change" notification, with a schedule and deprecation period.
* A temporary support for `channel=master` where using it shows a warning banner on the page, maybe or maybe not with a HTTP redirect (say to same URI `with `channel=master` changed to `channel=main&deprecation=master-channel`, or something, which could use that URI to trigger showing the warning).
That could then allow automatic testing of URIs at the Flutter end, checking if the URIs they expose do not get a "permanent redirect" HTTP response, which would be a signal to update the URIs.

**Comment by johnpryan** [comment]
I'm going to close this for now, since we are aliasing `master` to `main`. 

DartPad doesn't have a huge API surface, we support a handful of query parameters for the Gist ID, the theme, and the UI mode (mobile or desktop). We should probably document that better in the [embedding guide](https://github.com/dart-lang/dart-pad/wiki/Embedding-guide). 

I can't think of a way for DartPad to integrate with our documentation tooling to say whether or not a snippet still compiles and runs, but I'm happy to discuss any ideas anyone might have to solve that.
