### ISSUE TITLE
Run button doesn't indicate program will likely fail, if there is a hint

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#302]
![screen shot 2015-04-09 at 9 42 33 am](https://cloud.githubusercontent.com/assets/5479/7071832/c8c6b2e8-de9c-11e4-842b-fb06987ac3c9.png)

We've changed the Run button's display when we have warnings and errors. What about hints like this one?

**Comment by kasperpeulen** [comment]
I thought that blue ones are not very likely to break a program, but this one seems like it could easily do. I don't understand why this one is blue, while this one is yellow:

![image](https://cloud.githubusercontent.com/assets/1035299/7071970/0957d3c2-dee9-11e4-9179-be069fa4d080.png)

**Comment by sethladd** [comment]
Your screenshot is yellow because x is marked as an int, so the spec's warning kicks in.

My screenshot is a "hint", because x is dynamic. The spec doesn't say anything about dynamic variables calling "wrong" methods.

Perhaps we need two categories of hints from the analyzer:

* This hint means your program will probably not run.
* This hint is for code hygiene

**Comment by lukechurch** [comment]
@bwilkerson @stereotype441

**Comment by stereotype441** [comment]
One of the reasons the analyzer is gentle about hints is that Dart's semantics are loose enough that it's hard for a static analysis tool to tell the difference between "probably will not run" and code hygiene.  For instance, consider this code:

    f(List x) {
      var y = x;
      y.foo();
    }

Is this bad code hygiene?  Definitely.  Will there be a problem when the code is run?  It depends on the runtime type of the value of x passed to f().  If the runtime type of x is just a plain List, then trying to call .foo() will throw an exception.  But if the runtime type is a user-defined subtype of List, it might implement its own .foo() method, so the code will be fine.

One possible solution would be to have the analyzer make a distinction between situations where the function will throw an exception regardless of the runtime types of the data it accesses, and situations where there might be types that cause the function to succeed.  For instance, this code will always throw an exception because it's impossible to make user-defined classes that are subtypes of int:

    f(int x) {
      var y = x;
      y.foo();
    }

This code will also always throw an exception, but it's harder to tell, because it requires analyzing the List constructor to verify that it can never return a subtype of List that implements foo():

    f() {
      var y = new List();
      y.foo();
    }

Things get even more subtle if the function has control flow, so the problematic line might not even get executed; or if it has exception handling to catch the NoSuchMethod exception.

My suspicion is that in practice, even if we make the analysis much more sophisticated than it currently is, most hints in real-world code will still fall into the category of "code hygiene" rather than "probably won't run".  So I'm not convinced that the distinction would produce a huge amount of benefit

**Comment by kasperpeulen** [comment]
@stereotype441 I was trying to play around with this. I'm not an expert on the dart language, so probably I get this wrong, but say you have this code:

```
class A {
  foo() => print("1");
}

class B extends A {
  foo2() => print("2");
}

void main() {
  var a = new A();
  a.foo();
  a.foo2();
}
```

I would think that a.foo2() should always give an error/warning, even if there is an subtype of A that implements foo2(). I mean you should have new B() to make sure foo2 is available, or am I missing something here ? The dart analyser doesn't give an "info" warning here, while the program crashes at dartpad:
https://dartpad.dartlang.org/8987bfe58ae08ece4be3

**Comment by stereotype441** [comment]
@kasperpeulen There's two questions here: 1. how could the call to foo2() ever possibly succeed? and 2. why doesn't the analyzer give a hint for the call to foo2()?

The answer to the first question is that if A's constructor is a factory constructor, it's not guaranteed to return an object of type A.  In checked mode it's allowed to return any subtype of A.  (In fact, in unchecked mode it could return any type at all, but the analyzer assumes that it's going to return a subtype of A).  This is actually a pretty common design pattern in the Dart SDK and many of the libraries published on pub: we make a public base class that exposes the behaviors the client is intended to use, and we make a private implementation class that extends (or implements) the public base class and provides additional implementation behaviors that we don't want to expose to the client.  Then we put a factory constructor in the public base class that redirects to the private implementation class.  That way the client doesn't even have to know that the private implementation class exists; they just call the base class constructor and behind the scenes the private implementation class gets created.

The reason the analyzer doesn't give a hint for the call to foo2() is because when the user declares a variable using "var" or "dynamic", they're essentially saying to the toolchain "trust me, I know what I'm doing with this variable, and I don't want to see warnings for it."  We don't want to give them a spurious hint unless we are really certain that the call is not going to work.

So what the analyzer does when it encounters "a.foo2()" in your example is this: it analyzes the variable "a" and determines it to be either A or a subtype of A.  (It doesn't look at A's constructor to see whether or not it's a factory constructor because one of our design principles is that we want the implementor of a class to be able to change the class's private implementation details without affecting the clients of that class; whether or not a constructor is a factory is a private implementation detail.)  Then it looks up "foo2" in class A and doesn't find it.  Then it looks at the subtypes of A* to see if any of them declare "foo2".  And indeed, B declares "foo2".  Since "a" is declared using "var", the analyzer assumes you know what you're doing and don't want to see spurious hints, so it doesn't complain.

(*Technically the analyzer doesn't look at all the subtypes of A, just the ones declared in libraries reachable from the current file.  But that detail hardly ever makes a difference in practice.)

If you comment out the line 'foo2() => print("2");' in your example, you'll see the hint appear.

**Comment by kasperpeulen** [comment]
Thanks for your explanation:) @stereotype441  

That is good to know, as I use 
`var div = new DivElement();`

just as a shorthand for 
`DivElement div = new DivElement();`

But maybe I could actually better write the last one, in this case, to get better tooling?

**Comment by devoncarew** [comment]
I generally annotate the left hand side with types. I'm mostly doing it for documentation purposes; it does get me a little better tooling as well. Doing it doesn't follow the dart style guide 100% though -

**Comment by devoncarew** [comment]
We changed the run button to indicated whether running will likely work or not.
