### ISSUE TITLE
Gist hex ID text is not obvious, looks like gibberish

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#304]
![dartpad__ __and_iot-developer-landscape-2015_enterprise_pdf_-_google_drive](https://cloud.githubusercontent.com/assets/5479/7071966/8cebd1d0-de9d-11e4-9772-1610eb2bc67a.png)

How about simply "Gist" ?

**Comment by devoncarew** [comment]
`Gist`? `View Gist`?

**Comment by sethladd** [comment]
Drop the "view". It's cleaner.

**Comment by kasperpeulen** [comment]
@sethladd Doesn't look that good imo, maybe make it a button ?
![](http://i.imgur.com/Lz1KthW.png?1)

**Comment by sethladd** [comment]
Thinking about the flow.

1. I edit code.
1. I click Share, and I get a link to share.
1. I edit my code again, and now the link is invalid.

Once I hit step 3, I probably want the share link to go away, and the Share button to re-enable. I also probably want the URL to change, because once I change my code, the URL (which includes the gist ID) is not longer correct.

Should we just change the Toast to say:

"A snapshot of your code was saved to gist.com/2fu23f923f8h29fh823f. Copy this link to share."

And who cares if the user clicks Share twice... if no code was edited, just give them the previous link. If the code was edited, create a new link.

IOW treat "Share" button as "Show me the permalink for this code"

**Comment by devoncarew** [comment]
I link having the hyperlink to the current gist, as it helps users to discover where the code they shared lives.

We are updating the URL automatically after each share, to reflect the new (current) location of the code.

The `Share` button right now acts now more like 'Commit changes (and fork)' than anything else. We're calling it share as that's nice and short; the meaning is a bit overloaded.

**Comment by devoncarew** [comment]
And I think the flow will naturally change when we roll out authenticated sharing.

**Comment by milanz-syus** [comment]
Not sure I can comment on a closed issue, but I agree with the need described by sethladd: 

1) I'd like to be able to, change and save (update) an existing gist, rather than always fork on a new change. This would obviously require a github login.
2) Optionally, be able to name the gist so the name is descriptive (or at least able to add a descriptive part of the name)

**Comment by milanz-syus** [comment]
Not sure I can comment on a closed issue, but I agree with the need described by sethladd:

1) I'd like to be able to, change and save (update) an existing gist, rather than always fork on a new change. This would obviously require a github login.
2) Optionally, be able to name the gist so the name is descriptive (or at least able to add a descriptive part of the name)
