### ISSUE TITLE
Resizing the code editor area width is tedious when the code contains long strings

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart-pad#311]
See https://dartpad.dartlang.org/a5170ff293b861b3db6b
Resize the editor to about 5cm (so that the url is wrapped several times) and then try to make it wide again.
I either have to move the mouse very slowly or dragging stops after a few millimeters.

**Comment by kasperpeulen** [comment]
I had this problem the first time I tried dartpad (2 weeks ago), but for some reason this issue went away for me. Maybe this is also linux specific ?

**Comment by zoechi** [comment]
Yup, I'm on Linux. This time also in Dartium.

**Comment by devoncarew** [comment]
I think what's happening here is that the mouse events are being swallowed by the iframe. To confirm, you can try resizing again, but make sure your cursor is lined up with the console/documentation section, rather than the DOM output area (which contains the iframe).

We have a 16 px margin between the center of the splitter and the iframe - that's the buffer where if you move your mouse slow enough, the iframe won't get the mouse move event :(

To fix, we'd need to capture the mouse events in the iframe itself. If they're not consumed by the dart app in there, we'd proxy them out to the embedding page and adjust the coords.

**Comment by kasperpeulen** [comment]
@devoncarew I can reproduce this issue at chrome/firefox mac if I line up my cursor with the iframe.

In firefox it gets really weird, it won't notice that I released my mouse after dragging, and it will be dragging the splitter until I refresh the page.

**Comment by kasperpeulen** [comment]
@devoncarew what about setting pointer events to none on the iframe when the dragging begins? And then setting it to normal again when the dragging is finished.
