### ISSUE TITLE
Provide a textual description of the gist/pad

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#344]
Presuming that we can improve our SEO by adding more information about the pad in the gist's README, I wonder if we should provide a textual representation of the code.

For example:

"This code uses dart:async, Future, and for loops."

Can we auto-generic a description of the semantics of the code? If that's too difficult, can we auto-generate a description of the syntax of the code?

I think about the case where a user types something like this into their favorite search engine: "futures loops" or "dart future async loops". If they type that in, should they find our pads?

**Comment by kasperpeulen** [comment]
I think github does something so that it is very hard to search for anonymous gists. For example if I search for:

`This method answers the ultimate question. Future doAwesomeThing() => new Future.value(42);`

at the google search engine, then it won't find your gist. It will find my gist (that I forked form your gist) that is not anonymous.

**Comment by sethladd** [comment]
Wow, it finds your gist that fast? That's cool.

Regardless, we'd find the description valuable for any gist (anonymous or identified).

**Comment by kasperpeulen** [comment]
Maybe this "google search engine" gives some special treatment to pages with dart code ^^ ?

**Comment by devoncarew** [comment]
done -
