### ISSUE TITLE
Results area not scrollable on mobile safari 

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dart-pad#366]
See https://dartpad.dartlang.org/6d3d57526b0c790d9e86

On mobile Safari the results area extends down into the privacy policy and send feedback area, and I can't scroll it. Since that's the whole point of what I'm trying to test, it's less good.

**Comment by devoncarew** [comment]
@alan-knight, I don't have mobile safari to hand - can you try http://dev.dart-pad.appspot.com/6d3d57526b0c790d9e86 and see if you see an improvement?

**Comment by alan-knight** [comment]
That's better. With that version I don't see the Run part until I click the Play button. That button is mostly offscreen to start with, and there isn't an obvious scroll cue, but I can move it up and click it. I don't know what the green slider on the run screen does, and there's a light blue area at the bottom that comes up when I scroll. But it's definitely better than the overlapping I was seeing before.

**Comment by devoncarew** [comment]
OK, so I'd forgotten that we turned on mobile redirect on the dev server. So you're seeing an entirely different UI. That one was designed specifically with mobile (and phone size displays) in mind. Sounds like there may be some drawing issues with the console output on the mobile UI w/ safari.

FYI, the green toggle is meant to show and hide the console output area. The top is used to display any DOM output.

I think our app is slightly too tall on mobile safari - you shouldn't have to do any vertical scrolling to use the UI. Possibly we're too tall because of the browser's toolbar?

**Comment by alan-knight** [comment]
OK, so the console output area is the unlabeled light blue area at the bottom. It wasn't clear if it was supposed to be a separate area or was just a scrolling artifact. It could use a label, or border, or something to indicate it's intentional. My HTML is larger than the screen, so I didn't notice the slider turning it on and off.

If I push up on the page so the browser toolbar is at minimum size then I can see the run button. But if I have it pulled down so I have the toolbar buttons and the browser tabs visible then it's almost off-screen.

**Comment by devoncarew** [comment]
OK, thanks for the report. Definitely a mobile iOS-ism.

**Comment by devoncarew** [comment]
@alan-knight, there's a new version available at http://dev.dart-pad.appspot.com which _should_ fix the iOS long content issue.

**Comment by alan-knight** [comment]
Yes, it seems to.
