### ISSUE TITLE
UX regression: Pads using HTML don't display HTML OUTPUT by default

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dart-pad#488]
This is a UX regression, the problem is that you follow a link to an HTML pad, e.g. https://dartpad.dartlang.org/778c6a64c71c474dde71 and hit run, and nothing appears.

This gives the impression that DartPad is broken, it's pretty difficult to discover the need to click "HTML OUTPUT' and even when you discover it, it can be difficult to remember to do. I've made the same mistake a number of times in the past hour.

Can we look at bringing back automatically showing the HTML OUTPUT tab by default pads with HTML.

**Comment by devoncarew** [comment]
@Georgehe4, can you take this? I think we want to auto-change tabs on run again.

**Comment by Georgehe4** [comment]
Yeah. We have a few trade-offs to consider.
We definitely want to do auto-switching based off of Luke's observations.
One possibility presents itself:
-Checking of console output is null. If it is, switch to html.
-Check if there is any html. If there is not, switch to console.
-If both are present, don't do anything.
I will work towards this. Lmk if you have any other suggestions.

**Comment by devoncarew** [comment]
I think we can boil the logic down to:

- if the html source isn't empty, then it's an html sample (`html.trim().isNotEmpty`)
- if the dart code imports `dart:html`, then it's an html sample (contains `'dart:html'` or `"dart:html"`)
- otherwise, it's a console sample

This is a slight variation on this logic https://github.com/dart-lang/dart-pad/blob/master/lib/playground.dart#L542.
