### ISSUE TITLE
Html links with target _blank don't work

### ISSUE THREAD

**Issue by dafesimonek** [dart-lang/dart-pad#709]
Copy & paste following piece of html into dartpad

<a href="https://dartpad.dartlang.org/" target="_blank">DartPad with _blank target</a>
<a href="https://dartpad.dartlang.org/" target="_top">DartPad with _top target</a>

Links with such targets seem to not work, while "normal" links do work.

**Comment by RedBrogdon** [comment]
We've sandboxed the execution iframe (which displays DartPad's web output) as a precaution, and that's the root of cause of this behavior. There *are* flags that can be set to get around this, but unless folks are really banging at the door asking for it, I'd prefer to leave things as secure as possible.

Closing this for now, since it's 3.5 years old and hasn't been requested again in that time. Anyone really bothered by the behavior is free to reopen, though.

CC @domesticmouse

**Comment by domesticmouse** [comment]
+1 for being secure.
