### ISSUE TITLE
completion in method body does not work unless 'this.' is used

### ISSUE THREAD

**Issue by pstjvn** [dart-lang/dart-pad#712]
The completion for instance fields does not show when starting to write the field name in the same class method. However when in the same method body I type 'this.' the fields and methods in the class are automatically popping out which in turns leave the impression that 'this.' is the preferred / desired way of referring to class methods and properties in the method body of a class.

**Comment by devoncarew** [comment]
cc @danrubel

**Comment by RedBrogdon** [comment]
This behavior persists in the current release. It seems to result from our choice to show suggestions only in response to Ctrl-space or a period after an identifier. If you manually press Ctrl-space inside a class method, fields are correctly suggested without `this`.

I'm not sure if we should change the completion behavior to fix this, since it would result in a ton of unnecessary/unwanted completion requests to the server. Is adding [`unnecessary_this`](https://dart-lang.github.io/linter/lints/unnecessary_this.html) as a lint option possible?

@domesticmouse @devoncarew

**Comment by domesticmouse** [comment]
@redbrogdon I’m confused on how adding `unnecessary_this` to the mix helps in this specific instance.

With that said I’m all for adding lints to the build environment to give guide rails to the developer using dart-pad to explore the dart language.

**Comment by RedBrogdon** [comment]
I was suggesting it as a way to address this bit:

>...which in turns leave the impression that 'this.' is the preferred / desired way of referring to class methods and properties in the method body of a class.

If we choose to leave completion as-is, including that lint would at least prevent the impression that people are expected to use "this." when accessing properties from inside a class's methods.

**Comment by domesticmouse** [comment]
Ahh, right. +1 for adding lints.

**Comment by parlough** [comment]
I can no longer reproduce this issue and DartPad now is setup to use the core set of recommended lints from `package:lints`.

Thanks again for the issue and details! If you experience more completion issues, please open a new issue with reproduction details.
