### ISSUE TITLE
Only "Uncaught" shown for some errors

### ISSUE THREAD

**Issue by filiph** [dart-lang/dart-pad#737]
Running https://dartpad.dartlang.org/bad57c341ff1dbbc8e7464cd458b124b shows:

> Uncaught

instead of something like

> CastError: Casting value of type JSArray to incompatible type num
#705 related or the same?

**Comment by Zectbumo** [comment]
main(){x;} error also only shows "Uncaught"

**Comment by jcollins-g** [comment]
That was too easy -- apparently the test case I tried works even without the change.

**Comment by jcollins-g** [comment]
The problem seems to lie in whatever is generating calls to the [function defined for](https://github.com/dart-lang/dart-pad/blob/ff20c30170fea6ea0b4c5babf0a2b99f6d9cc74c/lib/services/execution_iframe.dart#L58) the javascript [window.onerror](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) handler.

Since I don't think I can directly control that without modifying the user's browser(?), the proposed fix in #826 expands that handler to include the error object, a relatively new extension not filled in by older browsers.

There are apparently at least two ways exception data makes it to this handler:

1) `message` contains the complete error message, and the `errorObject` contains the same data as the end of the message.
2) `message` contains a partial error message, and the `errorObject` contains the rest of the message.

So #826 hacks this by detecting whether or not `message` ends with `errorObject` and if it does, only display `message` -- but add `errorObject` otherwise.  The results seem to look good in the cases I've tested so far, but that's only Chrome on Linux.  I'll give it a try with some other platforms too.
