### ISSUE TITLE
Can't easily tell what version of Dart that DartPad is using?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart-pad#742]
Wanted to play with strong mode, wasn't sure how up-to-date DartPad is?

**Comment by devoncarew** [comment]
If you click on the 'DartPad' text on the upper left, that'll open a version dialog:

<img width="440" alt="screen shot 2016-09-16 at 6 43 38 pm" src="https://cloud.githubusercontent.com/assets/1269969/18605104/95cfcd8a-7c3d-11e6-9b60-dd999f1316e9.png">

@lukechurch will be in town next week, and we're planning to talk about rev'ing dartpad.

And, somewhat related, @pq recently moved flutter to using the analyzer version from the sdk (https://github.com/flutter/flutter/pull/5900), which has the very nice property that the analyzer we're using is exactly in sync with the sdk version (instead of whatever the last published analyzer was); probably something to adapt in dartpad when we have bandwidth.

**Comment by sethladd** [comment]
Ah, thanks!
