### ISSUE TITLE
Add dartfmt button

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-pad#752]
Would be great to format code before I share it...

**Comment by Sfshaza** [comment]
YES YES YES! I frequently paste code into dartfmt to test it, perhaps check for strong mode errors, etc. The formatting is often wonky after pasting or after I've diddled the code. I'd like to then run dartfmt over it so I can then copy and paste it into, say, a doc.

A strong +1!

**Comment by Sfshaza** [comment]
Is it possible to raise the importance of this issue? I am using DartPad (and only DartPad) for a Google I/O codelab and it's really awful that there is no way for users to format the code.  (This is for a "Java to Dart" codelab and I'm having the participant modify Java code to convert it to Dart. The formatting is vital for this to look good, especially since Java uses 4-character indentation.)

@devoncarew   @lukechurch   @kevmoo  @kwalrath   @filiph   @sethladd
