### ISSUE TITLE
Load content from any GitHub repo path

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart-pad#788]
This requests for an alternative solution to the problem reported in #637. Namely, that it be possible to load DartPad content from any given GitHub repo path, such as https://github.com/dart-lang/site-www/tree/master/examples/language-tour/args/bin.

This example DartPad would be access via `?id=dart-lang/site-www/tree/master/examples/language-tour/args/bin`.

Or more generally in the GitHub REST API: `?id=:owner/:repo/:path`

cc @kwalrath @Sfshaza

**Comment by kwalrath** [comment]
cc @RedBrogdon

**Comment by RedBrogdon** [comment]
Added #1096 to track the ability to load individual exercises from a repo that houses a collection of them. We might still want to do this, though, so I'm leaving it open.

**Comment by parlough** [comment]
This was supported in a limited capacity but the newest frontend doesn't support it, due to the more focused scope. I'll close this in favor of https://github.com/dart-lang/dart-pad/issues/2733 and https://github.com/dart-lang/dart-pad/issues/2871 which may be alternatives worth exploring.

If anyone would still like to see this implemented, please open a new issue. Thanks so much!
