### ISSUE TITLE
change dartpad language tour use cases from embedded snippets to a TOC style UI

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#821]
The idea here is to:
- remove embedded dartpads (like in the language tour)
- instead, move to a TOC style full-page UI (similar to try.kotlinlang.org and others)

The two goals here being:
- we think the TOC style would be a superior way to explore and teach the language
- overall, reduce the maintenance cost of dartpad (the embedded version os written in Polymer, which has a higher overall maintenance cost. A TOC UI would hopefully share much of its code with the desktop version of the dartpad UI).

**Comment by chalin** [comment]
I see two distinct DartPad issues here:

1. **Add support for TOC style full-page UI**.
  So the goal would be to offer an IDE-like experience with a TOC-style project explorer pane? https://stackblitz.com is another remarkable example (which, as you probably know, is used by the Angular TS team - 
  Is there a separate issue to track the evolution of this feature?
2. **Deprecate support for embedded DartPads**.

Online IDEs like Stackblitz are great! Note that (1), seems to contradict #820: if we're going to offer an IDE-like experience with a TOC-style project explorer pane, it wouldn't make sense to disallow the editing of HTML and CSS files.

Of course, we'll need a transition period between the completion of (1) and (2). /cc @kwalrath

**Comment by devoncarew** [comment]
https://stackblitz.com looks great! I had not been aware of it.

> So the goal would be to offer an IDE-like experience

I would walk that back a bit; this would be a TOC of organized snippets on the left - with a general theme, like learning Dart - and a single editor pane on the right. Selecting a topic would replace the editor's text. We wouldn't try and have multiple editors or editor tabs, or have a sophisticated persistence mechanism.

Agree that 1) and 2) are conflated, but likely to keep DartPad maintainable overall, we'd trade one feature for the other.

**Comment by RedBrogdon** [comment]
I'm hijacking this bug for the Q1/Q2 project. Based on the plans we've ironed out in the past couple of weeks, the tasks here would go from:

* remove embedded dartpads (like in the language tour)
* instead, move to a TOC style full-page UI (similar to try.kotlinlang.org and others)

to:

* Create a new embedded UI to use dart:html rather than polymer and support some new features (like code verification via unit tests).
* Introduce a TOC-style list of snippets/lessons similar to try.kotlinlang.org (et al) to the full-screen DartPad UI.

These are large goals, so there will be a number of other issues referencing them.

**Comment by parlough** [comment]
Closing this in favor of https://github.com/dart-lang/dart-pad/issues/2702 and some other related work Marya and I are exploring. I'll update this comment with a link to that once a tracking issue is available. Thanks!
