### ISSUE TITLE
general feedback on the new embedding UI

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#978]
- the header resizes vertically when it adds a message (“Test failed. Did you forget to return a value?”); I think we should remove padding from the `div id="test-result"` element
- should minimize the use of different fonts and font sizes; the test-result uses `font-size: 12px;` - we should just elide that css
- I'm not totally sold on replacing the icon on a button during loading (the 'check code' button); disabling the button makes sense; perhaps also showing a progress loader elsewhere?
- when there’s output written to the console, how will users know that unless they’re looking at the tab?
- when loading embeddings, there's a flash of a dark color;  think this is due to `color: #333;` on the body element

@RedBrogdon @domesticmouse

**Comment by devoncarew** [comment]
- perhaps, rename 'Console' to 'Output'?
- we may want to do something so that the three 'Your code' / 'Test' / 'Console' buttons look more like tabs (they do look nice as is, but because their behavior is essentially tabs, we may want to change them to appear more like tabs)

<img width="281" alt="Screen Shot 2019-04-02 at 1 10 42 PM" src="https://user-images.githubusercontent.com/1269969/55432878-e769fd00-5548-11e9-937a-5c5124f86cc2.png">

**Comment by devoncarew** [comment]
- the console output needs some padding between it and the container
- when the user hits 'check code', we should clear any previous output in the Console

**Comment by RedBrogdon** [comment]
### Already fixed:

#### the header resizes vertically when it adds a message (“Test failed. Did you forget to return a value?”); I think we should remove padding from the div id="test-result" element

That label has been removed entirely in the current build. Test results are now in a flash popup at the bottom right of the screen.

#### the console output needs some padding between it and the container

This should be corrected in the current build.

#### when the user hits 'check code', we should clear any previous output in the Console

This should also be corrected in the current build.

### Can be fixed immediately:

#### should minimize the use of different fonts and font sizes; the test-result uses font-size: 12px; - we should just elide that css

Good point. The result label is gone, but the console is still using a different font size. I'll remove it.

#### when loading embeddings, there's a flash of a dark color; think this is due to color: #333; on the body element

There was an iframe { background-color: #333 } in the embeddings demo page itself. I copied mine straight from the original, which must have matched the old embed UI's background color. I'll take it out.

### Moved to separate issues:

#### we may want to do something so that the three 'Your code' / 'Test' / 'Console' buttons look more like tabs (they do look nice as is, but because their behavior is essentially tabs, we may want to change them to appear more like tabs)

Agreed. I just didn't have a better option at the time (with my limited knowledge of Primer). Added #982.

#### I'm not totally sold on replacing the icon on a button during loading (the 'check code' button); disabling the button makes sense; perhaps also showing a progress loader elsewhere?

You've voiced this concern before, and I think you're right. Added #981 to track.

### Not sure how to proceed:

#### when there’s output written to the console, how will users know that unless they’re looking at the tab?

Also a good question. What do you think about adding some kind of indicator to the console button? The number of lines or messages that are "unread?"

#### perhaps, rename 'Console' to 'Output'?

This may be a good question for UXR to answer for us.

**Comment by devoncarew** [comment]
- the font size in the editing area is too small
- the icon used for the 'reset code' button doesn't really seem to represent reset; perhaps just remove the icon (and only have one for the run button)?

<img width="139" alt="Screen Shot 2019-04-03 at 9 37 37 AM" src="https://user-images.githubusercontent.com/1269969/55496600-581a2380-55f4-11e9-90c5-df7c40fad1b9.png">

**Comment by devoncarew** [comment]
> Also a good question. What do you think about adding some kind of indicator to the console button? The number of lines or messages that are "unread?"

We have the option of using small, in-line badges (I forget the primer name for them); I don't know if this would work in practice, but worth trying:

<img width="217" alt="Screen Shot 2019-04-03 at 9 52 18 AM" src="https://user-images.githubusercontent.com/1269969/55497469-45085300-55f6-11e9-8c7e-3f3bc5e252bb.png">

<img width="223" alt="Screen Shot 2019-04-03 at 9 52 22 AM" src="https://user-images.githubusercontent.com/1269969/55497481-49347080-55f6-11e9-857d-a3a700d158f7.png">

**Comment by devoncarew** [comment]
- the analysis error prompt shows up very quickly as I'm typing; we may want a small delay between the last keystroke and when we do analysis, so that we don't show errors very quickly, while the user is still typing. Also, we may want to eliminate the `ERROR` prefix, or an least make it lower case, so it's less alarming.

<img width="432" alt="Screen Shot 2019-04-03 at 9 55 19 AM" src="https://user-images.githubusercontent.com/1269969/55497734-d8da1f00-55f6-11e9-9945-33619899d77d.png">

**Comment by RedBrogdon** [comment]
Closing, as I believe everything in this list has either been moved to another issue or fixed outright. New UI notes can be added as separate issues.
